### ISSUE TITLE
Google cloud documentation is outdated

### ISSUE THREAD

**Issue by gfinol** [lithops-cloud/lithops#1001]
I tried to use Google cloud with lithops following the current available documentation, but I found the following error:

```
Exception: ('project_name', 'service_account', 'credentials_path', 'region') is mandatory under 'gcp' section of the configuration
```
But according to [Lithops documentation](https://github.com/lithops-cloud/lithops/blob/master/docs/source/storage_config/gcp_storage.md#google-cloud-platform) only 'credentials_path', 'region' are the only mandatory keys.

**Comment by JosepSampe** [comment]
Which version are you using?

Currently reuired params are only `Region`
https://github.com/lithops-cloud/lithops/blob/73480bdb985690f4fc97eaebf9baa82bb5925fc3/lithops/storage/backends/gcp_storage/config.py#L20

**Comment by gfinol** [comment]
I was using 2.6. 

Updating to 2.7 solved the issue. I close it.
