### ISSUE TITLE
[BUG][AWS Lambda] Timeout limits are not correctly set

### ISSUE THREAD

**Issue by felipecaon** [lithops-cloud/lithops#1046]
When deploying a function in AWS lambda timeouts are not correctly read from .lithops_config file, this behavior results in a wrongfully generated Lambda function with a wrong timeout.

I believe this issue starts from a typo in `cli.py`, where `runtime_timeout` is defined as `runtime_memory` instead of `runtime_timeout`.

```python
runtime_timeout = runtime_info['runtime_memory']  
```

should be

```python
runtime_timeout = runtime_info['runtime_timeout']  
```

**Comment by JosepSampe** [comment]
@felipecaon Thanks for reporting that issue.

However, this is only called if you run `lithops runtime update` command. are you using this command? or did you experience this issue without this command? Can you provide more context information? lithops version, python version?

**Comment by felipecaon** [comment]
Hey @JosepSampe

Sorry for the lack of information, I wrote that issue in a hurry.

I was having a hard time setting up a lambda function with a proper runtime timeout. It turns out I was forgetting to add `runtime_timeout` into my lithops config file, my mistake and no bug whatsoever.

While trying to file the issue that caused my problem to arise, I found this unrelated bug.
