### ISSUE TITLE
Python 3.7 Lambda: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by ZikBurns** [lithops-cloud/lithops#1104]
When I run `lithops test` or any other invoke, I get:

> Exception: An error occurred: {'errorMessage': "Unable to import module 'entry_point': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: [https://github.com/urllib3/urllib3/issues/2168](https://github.com/urllib3/urllib3/issues/2168)", 'errorType': 'Runtime.ImportModuleError', 'stackTrace': []}
It creates lithops_v2-9-0_l3bm__lithops-default-runtime-v37_256MB and lithops_v2-9-0_l3bm_lithops-default-runtime-v37_layer

Lithops version: 2.9.0
Python version: 3.7
Configuration: 
- backend: aws_lambda
- storage: aws_s3

Temporary workaround:
1. Create a requirements.txt with the following packages:
```
lithops
urllib3==1.26.15
```
2. Create your own dependencies zip:
```
pip install -r requirements.txt -t ./python/
zip -r9 site-packages.zip python
```
3. Upload it to S3 and update the layer in the generic function

**Comment by aitorarjona** [comment]
Can confirm this is still an issue also for python39

**Comment by JosepSampe** [comment]
[Acording to this](https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html#importerror-cannot-import-name-default-ciphers-from-urllib3-util-ssl), botocore still does not suport urllib3 2.0, so https://github.com/lithops-cloud/lithops/pull/1122 should solve the issue.

@ZikBurns Can you try with master branch?

**Comment by CelioXavier** [comment]
I managed to resolve this error by including the following import in requirements.txt:

requests==2.18.4
google-auth==1.1.0

With that, my lambda started executing again.

Hugs!
