### ISSUE TITLE
Unexplained exception

### ISSUE THREAD

**Issue by oanamoc** [lithops-cloud/lithops#1119]
Hello, I have just started learning about lithops and I am intending to configure it to use it with amazon lambda and amazon s3. I've made a config.yaml file and the contents are these (instead of the placeholder text I have put my information):
lithops:
backend: aws_lambda
storage: aws_s3

aws:
access_key_id: YOUR_ACCESS_KEY_ID
secret_access_key: YOUR_SECRET_ACCESS_KEY
region_name: YOUR_REGION_NAME

aws_lambda:
execution_role: arn:aws:iam::923514422203:role/lithops-execution-role
region_name: YOUR_REGION_NAME

My issue is that when I run this line in terminal (I am in the folder the file is):
lithops test -b aws_lambda -s aws_s3

It tells me this:
Exception: 'aws' section is mandatory in the configuration
Which is obviously not the case, as you can see.

I imagine the solution is something very simple but I am just starting to learn, so I would appreciate the help.

Thanks

**Comment by JosepSampe** [comment]
Hi @oanamoc, Wich of the [options listed here](https://github.com/lithops-cloud/lithops/blob/master/config/README.md#configuration-file) are you using to configure Lithops? Note that none of them use the extension `.yaml`
