### ISSUE TITLE
Some libraries missing when installing Lithops

### ISSUE THREAD

**Issue by RaulGracia** [lithops-cloud/lithops#1163]
**Description of the problem**
When installing Lithops, the first time that I execute a job requiring S3 access, there is a failure as the library `boto3` is missing. I wonder if there could be a better check of the required dependencies and install all of them when running lithops installation (as it may happen also to other libraries). Once the library is manually installed, things work as expected.

**Comment by JosepSampe** [comment]
When installing lithops for a specific cloud, you have to specify which cloud are you using in order to install specific packages, for example:
`
python3 -m pip install lithops[aws]
`

https://github.com/lithops-cloud/lithops/blob/master/docs/source/compute_config/aws_lambda.md#installation

**Comment by JosepSampe** [comment]
In #1166 I included the `boto3` lib in the default installation dependencies, so from now on there is no need to explicitly execute `python3 -m pip install lithops[aws]` anymore for the AWS backends
