### ISSUE TITLE
Process CSV files in chunks suggestion

### ISSUE THREAD

**Issue by omerb01** [lithops-cloud/lithops#119]
something I suggest to improve pywren's adaptability for any large data handling projects:

CSV files are usually processed by packages like pandas which use `read_csv()` method and create an instance of an efficient data handler called "DataFrame".
source: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

highlight supported features with this handler:
- iterating over data lines
- indexing data for optimizations purpose
- computing data functions
- dividing data into categorized groups

I think it will be significantly better if PyWren will be integrated with this handler so for example we can read CSV data efficiently from COS in categorized groups chunks (or whatever alternatives) instead of always making dedicated pre-storing manipulated data files in COS and then with a simple logic change, we need to change everything manually again.

**Comment by JosepSampe** [comment]
@omerb01 I think that are well know the benefits of using pandas dataframes. I always use it when I need to efficiently read for example a CSV file, even with pywren. In the IBM-PyWren paper we write, I used pandas to work with AirBnB datasets. I mean, now, if someone wants to use a pd.dataframe, he only have to write:
```
def process_formulas_database(key, data_stream):
     my_df = pd.read_csv(data_stream)
```
And if someone don't want to use dataframe because he doesn't have (semi-)structured data, he dosn't need to do anything, just read the **data_stream** with **read()**.

So my question are: 

1. "we can read CSV data efficiently from COS" Are you saying that read data from pandas is more efficient than read raw data from data_stream? How can we do it? Did you test it?

2. What do you refer to "always making dedicated pre-storing manipulated data files in COS". How do you suggest to integrate pywren in pandas?

**Comment by omerb01** [comment]
@JosepSampe The main idea that made me open this issue is that currently PyWren's chunks logic is limited (only chunked size devision without breaking lines).

PyWren works usually with big data inputs so usually we need to implement parallel logic on the data which answers our purposes. In general, implement this desired parallel logic isn't always possible directly or isn't enough efficient and we need to implement pre-processes logics in addition to our code - for example, store separated parts from a large data file that have something in common.
in conclusion, When I use PyWren I would like to define my data chunks as ever I want to, (categorized chunks, chunked-size, n-chunks, iterate over lines, etc...) without being limited to a specific way, and also I would like to do it easily as possible, with minimum interfering of pre-processes implementations.

To do so, I have started to think about pandas which (as you know) has these abilities implemented already. I thought about giving a new parameter to `map()` method that will tell which type of data file we use (csv, txt, parquet, and maybe more types), and then PyWren will maintain a DataFrame stream from COS, currently don't sure how exactly.
in terms of efficiency - I think the main barrier that limits PyWren's integrations efficiency is the necessity of upload and download inputs/outputs from COS, if we will implement a smart chunks division, we sure get everything better with various intuitive implementation ways.

Also, in future, If we will manage to implement it, we could implement an indexing logic for chunks (store distributed data like Apache Spark does), and direct invocations to import indexed specific data parts without reading all data in parallel.

**Comment by JosepSampe** [comment]
Thanks @omerb01, I now fully understood what you suggest.

**Comment by JosepSampe** [comment]
Closing remark: Lithops provides to the users a low level storage interaction with the `obj.data_stream` parameter, which is the data from the object storage in raw format. Then the user is responsible to decide if the `obj.data_stream` is passed to the `pandas` library, to the `csv` library, or to any other library able to interpret csv files.
