### ISSUE TITLE
IBM VPC config issue

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#1205]
Hi!

The documentation states that `worker_processes` is not a mandatory parameter for IBM VPC. But in the code, this parameter is specified [as mandatory](https://github.com/lithops-cloud/lithops/blob/master/lithops/standalone/backends/ibm_vpc/config.py#L26).

**Comment by JosepSampe** [comment]
I added [this patch ](https://github.com/lithops-cloud/lithops/pull/1206)that, by default, automatically uses the cpu count of the VM as worker_processes. So now it is not mandatory
