### ISSUE TITLE
AWS Lambda function name

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#1210]
>> Is it possible to specify normal short names for lamda function? Currently, the auto-generated entities are very long and have redundant entities. Examle: lithops_v3-0-1_lhdm__metaspace-aws-lambda--301c_512MB.

> This was originally designed like this because this was supporting some internal logic so that from the function name we were able to get the container name, the memory and the user. Not sure if this is still necessary, need to check. In other backends we switched from these kind of names to lithops-worker-xxxxxxx where xxxxx is the hash of the function name you see. Would this work for you? or what is for you a "normal short name"?

I usually create names of docker images like `metaspace-aws-lambda:3.0.1` or `metaspace-ibm-ce:3.0.1` where in the tag I store the current version of lithops. I'd like to have full freedom to provide names, but `lithops-worker-xxxxxxxx` works fine for me as well.
Although I want to have separate lambda functions for different environments (production, staging) so I need to be able to specify this in the function name.

**Comment by sergii-mamedov** [comment]
I think this would be the best option considering the limitations of AWS Lambda.

**Comment by sergii-mamedov** [comment]
I only have one concern. For each new release of the lambda function, I will have a separate Log group in the Cloud Watch. I have already encountered this problem during tests.

**Comment by JosepSampe** [comment]
In this case, I'm not sure if it is a good idea to change and remove the "lithops" version from the function name. Changing this may introduce inconsistencies, as the current implementation relies on this specific naming convention to detect whether the corresponding worker version is deployed or not. Removing the name has the potential to lead to inconsistencies, as Lithops won't be able to determine which version contains the "function worker" being invoked.

**Comment by sergii-mamedov** [comment]
Ok, then I'll manually specify the name of the log group for the lambda function. Thanks a lot.

**Comment by aitorarjona** [comment]
@sergii-mamedov would a configuration key to specify the log groups to attach the function to solve your issue?

**Comment by sergii-mamedov** [comment]
@aitorarjona yes
