### ISSUE TITLE
[Enhancement] Allow runtime_cpu to be passed as an argument for the FunctionExecutor for k8s

### ISSUE THREAD

**Issue by abourramouss** [lithops-cloud/lithops#1281]
Hello,

For k8s, it would make sense to pass the runtime_cpu argument (see https://github.com/lithops-cloud/lithops/blob/master/docs/source/compute_config/kubernetes.md)

I can pass the runtime_memory as a FunctionExecutor argument to increase the available memory each worker has, but I cannot pass a runtime_cpu to increase-decrease the quantity of cpus.

**Comment by JosepSampe** [comment]
All the backend parameters can be already passed in the `FunctionExecutor()`. All the paremetsrs you set in `kwargs` are passed to the backend config. In the case of k8s you can pass [all these](https://github.com/lithops-cloud/lithops/blob/master/docs/source/compute_config/kubernetes.md#summary-of-configuration-keys-for-kubernetes).

For eaxmple:
```python
fexec = lithops.FunctionExecutor(backend='k8s', runtime_cpu='5')
```

**Comment by abourramouss** [comment]
> All the backend parameters can be already passed in the `FunctionExecutor()`. All the paremetsrs you set in `kwargs` are passed to the backend config. In the case of k8s you can pass [all these](https://github.com/lithops-cloud/lithops/blob/master/docs/source/compute_config/kubernetes.md#summary-of-configuration-keys-for-kubernetes).
> 
> For eaxmple:
> 
> ```python
> fexec = lithops.FunctionExecutor(backend='k8s', runtime_cpu='5')
> ```

Thank you, I was looking at the implementation of the FunctionExecutor and didn't see it.
