### ISSUE TITLE
Dependency improvements

### ISSUE THREAD

**Issue by tomwhite** [lithops-cloud/lithops#1324]
Lithops has a lot of dependencies in the base package, many of which are not needed when running Lithops.

There are a few things we could do here:

1. Move dependencies for backends into 'extra' packages
   * boto3 - move to `lithops[aws]` (see #1323)
   * ibm* - move to `lithops[ibm]`
   * kubernetes?
2. Make dependencies for optional features optional
   * redis
   * pandas/matplotlib/seaborn - for plotting
3. Remove unused dependencies
   * lxml

**Comment by JosepSampe** [comment]
If I'm not wrong, the `docker` and the `python-dateutil` packages can also be removed. I remember they were used in the past, but now I can't find any import of these libraries.

**Comment by JosepSampe** [comment]
@gilv Do you agree on moving IBM dependencies from the default installation to extra packages? so that when using an IBM backend, users will have to install lithops like this: `pip install lithops[ibm]`?

**Comment by JosepSampe** [comment]
Closing as completed
