### ISSUE TITLE
Grammar on home page ; singular/plural mismatch

### ISSUE THREAD

**Issue by JimCollinsDC** [lithops-cloud/lithops#1384]
It says "which makes Lithops ideal for this type of jobs." It should either be "which makes Lithops ideal for this type of job." or
"which makes Lithops ideal for these types of jobs."

**Comment by JosepSampe** [comment]
Fixed in [here](https://github.com/lithops-cloud/lithops-cloud.github.io/commit/fbb5a8ec9ae15a9f6d814c0168cb5dcf84607e5e), thanks for reporting @JimCollinsDC
