### ISSUE TITLE
Avoid using CLI tool for installation scripts

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#15]
Installation scripts, like `pywren/deploy_pywren.sh` and `runtime/build_runtime.sh` both use `bx wsk` CLI tool to create an action. We would like to explore how this can be avoided and use direct Python code to create actions. Such code already exists in ` https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren/pywren_ibm_cloud/cf_connector.py`. We should see how to use this code instead of dependency on CLI tool

**Comment by gilv** [comment]
@JosepSampe thanks ;)

**Comment by JosepSampe** [comment]
@gilv Done in #18
