### ISSUE TITLE
pywren_ibm_cloud 1.3.1 tests hang when running in Python 3.6.9 and 3.6.10

### ISSUE THREAD

**Issue by robertgo-IBM** [lithops-cloud/lithops#258]
`python3 -m pywren_ibm_cloud.tests`, using Python 3.6.8, runs successfully to completion:

`docker run --rm --name clean-python-environment -v $PWD:/root python:3.6.8  bash -c 'pip3 install pywren_ibm_cloud==1.3.1; python3 -m pywren_ibm_cloud.tests'`

However, using Python 3.6.9 or 3.6.10, the first test simply hangs indefinitely:

`docker run --rm --name clean-python-environment -v $PWD:/root python:3.6.9  bash -c 'pip3 install pywren_ibm_cloud==1.3.1; python3 -m pywren_ibm_cloud.tests'`

**Comment by JosepSampe** [comment]
Unfortunately 1.3.1 had a bug that prevented to run the tests successfully. Can you try with >1.4.0?

**Comment by JosepSampe** [comment]
Working in Lithops
