### ISSUE TITLE
Notebook dependency Issues urlib

### ISSUE THREAD

**Issue by rmey** [lithops-cloud/lithops#297]
With default Watson Studio 3.6 Python Environment I had to downgrade urlib in the example Notebooks
`from time import time
from random import random
import logging
import sys
try:
    **!python -m pip install "urllib3<1.25"**
    import pywren_ibm_cloud as pywren
except:
    !{sys.executable} -m pip install pywren-ibm-cloud
    import pywren_ibm_cloud as pywren`

**Comment by JosepSampe** [comment]
What was the error/exception?

**Comment by rmey** [comment]
Similar like this: https://github.com/urllib3/urllib3/issues/1571

**Comment by JosepSampe** [comment]
Currently urlib is not pinned anymore in requirements. So there is no need to use specific urllib version
