### ISSUE TITLE
different output errors with Jupyter and Terminal

### ISSUE THREAD

**Issue by omerb01** [lithops-cloud/lithops#317]
I experience different output errors when a single action raises an exception.
the difference is:
1. In Jupyter notebooks, the full Traceback is printed while in Terminal only the relevant user code traceback is printed.
2. In Terminal, when an exception is raised, its associated action's activation ID is printed while in Jupyter notebooks its activation ID is never printed.

**Comment by gilv** [comment]
@omerb01 different logging level?

**Comment by omerb01** [comment]
@gilv Nope, it isn't the case, the printed output that I mentioned above happen with all logging levels
