### ISSUE TITLE
partial failure

### ISSUE THREAD

**Issue by Albert65** [lithops-cloud/lithops#329]
Hello,
When I run many training jobs simultaneously, some of them can fail for whatever reason (timeout, absent package, etc). I would tolerate, say, 5% of failures as soon as 95% of jobs succeeded. However, get_result() fires an exception, even if a single job did not return a result.  My question: is it possible to get result in case of partial failure? Could you provide an example in documentation?

**Comment by JosepSampe** [comment]
@Albert65 You can get available results and ignore exceptions by setting `throw_except=False` in `get_result` method: `pw.get_result(throw_except=False)`

https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/api-details.md#executorget_result

**Comment by Albert65** [comment]
I think, I tried this way, but still get exception. Let me take another attempt.
