### ISSUE TITLE
Be more verbose when missing out leading "http" on endpoint configuration

### ISSUE THREAD

**Issue by romeokienzler** [lithops-cloud/lithops#347]
Depending on which endpoint you've been missing out the "http" you get either clear or unclear feedback

unclear:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-9fcaa9d4304f> in <module>
      1 import pywren_ibm_cloud as pywren
----> 2 pw = pywren.ibm_cf_executor()

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/__init__.py in ibm_cf_executor(config, runtime, runtime_memory, workers, region, storage_backend, storage_backend_region, rabbitmq_monitor, remote_invoker, log_level)
     38         rabbitmq_monitor=rabbitmq_monitor,
     39         remote_invoker=remote_invoker,
---> 40         log_level=log_level
     41     )
     42 

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/executor.py in __init__(self, config, runtime, runtime_memory, compute_backend, compute_backend_region, storage_backend, storage_backend_region, workers, rabbitmq_monitor, remote_invoker, log_level)
     80             pw_config_ow['remote_invoker'] = remote_invoker
     81 
---> 82         self.config = default_config(copy.deepcopy(config), pw_config_ow)
     83 
     84         self.executor_id = create_executor_id()

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/config.py in default_config(config_data, config_overwrite)
    133     logger.debug("Loading Compute backend module: {}".format(cb))
    134     cb_config = importlib.import_module('pywren_ibm_cloud.compute.backends.{}.config'.format(cb))
--> 135     cb_config.load_config(config_data)
    136 
    137     sb = config_data['pywren']['storage_backend']

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/compute/backends/ibm_cf/config.py in load_config(config_data)
     60         api_key = config_data['ibm_cf'].pop('api_key', None)
     61         namespace_id = config_data['ibm_cf'].pop('namespace_id', None)
---> 62         region = endpoint.split('//')[1].split('.')[0].replace('-', '_')
     63 
     64         for k in list(config_data['ibm_cf']):

IndexError: list index out of range

clear:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-3-9fcaa9d4304f> in <module>
      1 import pywren_ibm_cloud as pywren
----> 2 pw = pywren.ibm_cf_executor()

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/__init__.py in ibm_cf_executor(config, runtime, runtime_memory, workers, region, storage_backend, storage_backend_region, rabbitmq_monitor, remote_invoker, log_level)
     38         rabbitmq_monitor=rabbitmq_monitor,
     39         remote_invoker=remote_invoker,
---> 40         log_level=log_level
     41     )
     42 

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/executor.py in __init__(self, config, runtime, runtime_memory, compute_backend, compute_backend_region, storage_backend, storage_backend_region, workers, rabbitmq_monitor, remote_invoker, log_level)
     80             pw_config_ow['remote_invoker'] = remote_invoker
     81 
---> 82         self.config = default_config(copy.deepcopy(config), pw_config_ow)
     83 
     84         self.executor_id = create_executor_id()

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/config.py in default_config(config_data, config_overwrite)
    138     logger.debug("Loading Storage backend module: {}".format(sb))
    139     sb_config = importlib.import_module('pywren_ibm_cloud.storage.backends.{}.config'.format(sb))
--> 140     sb_config.load_config(config_data)
    141 
    142     return config_data

/opt/conda/lib/python3.7/site-packages/pywren_ibm_cloud/storage/backends/ibm_cos/config.py in load_config(config_data)
     26             raise Exception('The private_endpoint you provided to access to IBM COS is not valid')
     27         if not config_data['ibm_cos']['private_endpoint'].startswith('http'):
---> 28             raise Exception('IBM COS Private Endpoint must start with http:// or https://' class="ansi-blue-fg">)
     29 
     30     elif 'private_endpoint' in config_data['ibm_cos']:

Exception: IBM COS Private Endpoint must start with http:// or https://

**Comment by JosepSampe** [comment]
Fixed
