### ISSUE TITLE
Dynamic memory per invocation and not per executor

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#354]
Current design allows to define runtime memory once executor intitiated. For example

```
iterdata = [1,2,3]
lt = lithops.ibm_cf_executor(runtime_memory=2048)
futures = pw.map(my_map, iterdata)
```

and each out of 3 invocations of my_map uses 2GB of memory.

What i seek is dynamic memory per invocations and not static per executor.
For example, we need something like this

```
iterdata = [1,2,3]
memory = [128,256,2048]
lt = lithops.ibm_cf_executor()
futures = pw.map(my_map, iterdata, memory)
```
and 1st invocation will use 128MB, second 256MB and 3rd 2048MB.

@JosepSampe i realise it's not obvious change...what do you think? I came to conclusion it's must to have...

**Comment by gilv** [comment]
@JosepSampe i think on invoke we can provide the memory we need for the invoke..

**Comment by JosepSampe** [comment]
@gilv you can already do this with `runtime_memory` param in each `map()` call ;) 
https://github.com/lithops-cloud/lithops/blob/master/docs/api-details.md#executormap

**Comment by JosepSampe** [comment]
@gilv Now you can provide the `runtime_memory` in each `map()` instead of in the executor, but not for each call within one `map()`

**Comment by gilv** [comment]
@JosepSampe i want one map and each invoke in the map will use different memory as may be provided in the input..similar to example i posted above. This seems to be very important for dynamic memory scenarios

**Comment by gilv** [comment]
@JosepSampe in the future we may even want to inject some function to calculate memory per invocation..but it's too early for that
