### ISSUE TITLE
Reserved function parameters should be clearly documented

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#356]
A user wrote a function ```def my_func(obj): <his code>.``` Execution failed without clear error. Eventually turned out that "obj" parameter is reserved in Lithops.
We should clearly document what params are reserved to prevent further similar issues.

**Comment by JosepSampe** [comment]
They are now specified in this document: https://github.com/lithops-cloud/lithops/blob/master/docs/functions.md#reserved-parameters
