### ISSUE TITLE
Possible wrong approach in IBM_VPC

### ISSUE THREAD

**Issue by JosepSampe** [lithops-cloud/lithops#362]
Now all the communication with the remote client is located within docker_executor, and I think it is not the correct place to put it. IMO we should follow the same approach as the pywren guys and create a `standalone_executor()` http://pywren.io/docs/#standalone-mode.

Put the logic in the docker_exeutor() prevents other ways of execution, since a user can use a docker image or a virtual environment, or simply use the default python interpreter and packages installed in that machine. 

IMO, we should create a `standalone_execuo()` and then, if a user provides a docker image, it will use that docker image as env to run the functions, and if a user provides nothing, it will use the default python interpreter of the machine.. In the future, if a user provides a virtualenv.zip in COS, it will use that virtualenv.zip

In addition, now in this mode of execution some things as missing, such as configurable cpu, memory and number of instances in runtime, so I plan to add these things in such a way a user can do something like this in runtime:
       lithops.standalone_executor(cpu=4, mem=16, instances=2)

Also, currently config keys of standalone are dispersed between lithops and ibm_vpc section, and most of those keys are generic, not attached to ibm_vpc, such as soft/hard timeouts. I think we should create a new section called "standalone" and place everything there, this way it is easy to switch between standalone backends keeping all common config variables without repeating them, for example:

```
standalone:
    backend: ibm_vpc
    cpu: 4
    mem: 16
    instances: 1
    auto_dismantle: True
    hard_dismantle_timeout: 10800
    soft_dismantle_timeout: 300
```

**Comment by gilv** [comment]
@kpavel @erezh16 what is your input on this one? Thanks

**Comment by kpavel** [comment]
@JosepSampe Can you please clarify where exactly "the IBM_VPC logic is located within docker_executor"? I think we already moved all the IBM_VPC logic our of docker executor in the #350

**Comment by JosepSampe** [comment]
@kpavel I mean all the ssh communication with the IBM VPC is located in the docker executor

**Comment by kpavel** [comment]
@JosepSampe can you please point me to the code?

**Comment by gilv** [comment]
@JosepSampe any input?
