### ISSUE TITLE
should `lithops clean` also call compute's engine method "delete_runtime" ?

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#374]
Today it's not call "delete_runtime". Should it?

@JosepSampe ^^

**Comment by JosepSampe** [comment]
`lithops clean` already calls delete_runtime method

**Comment by gilv** [comment]
@JosepSampe where do you see it in the code?

**Comment by JosepSampe** [comment]
https://github.com/lithops-cloud/lithops/blob/master/lithops/cli/utils.py#L42

This method internally calls one by one the delete_runtime()

**Comment by gilv** [comment]
@JosepSampe but this clean doesn't delete runtime?  or i missed something obvious

```
    futures = pw.map(my_map_function, iterdata)
    print (pw.get_result())
    pw.clean()
```

**Comment by gilv** [comment]
@JosepSampe i see what i missed. lithops clean calls delete_all_runtimes() and not delete_runtime(). Thanks.
