### ISSUE TITLE
job clean method is bombing COS

### ISSUE THREAD

**Issue by JosepSampe** [lithops-cloud/lithops#380]
With current additions with code engine logic, now the clean method makes as many requests to COS as functions where spawned.
For example, If you run a map with 1000 activations to IBM CF, it then makes 1000 requests to COS. In addition, this process now takes minutes to finish due this large amount of request. 

In the previous approach only 1 or 2 requests was required to do the same task, and the process finished in few seconds.

**Comment by gilv** [comment]
@JosepSampe what caused this? clean() method does nothing, unless it' code engine? Can you point to the code where it happens? It's the same clean method we can had before

**Comment by gilv** [comment]
@JosepSampe code engine backend doesn't clean data from COS. I wonder what caused the behaviour you observe.

**Comment by JosepSampe** [comment]
@gilv you changed granularity here: https://github.com/lithops-cloud/lithops/blob/master/lithops/job/job.py#L273
So now it makes one clean request per activation. i.e. 1000 activations = 1000 requests to COS

**Comment by gilv** [comment]
@JosepSampe because of activation_id?? I didn't noticed it screwed things.. i will fix it

**Comment by JosepSampe** [comment]
@gilv yes, it is because activation_id, but I think when we have array-based jobs on code engine, we will not need to call invoker.clean() here

**Comment by gilv** [comment]
@JosepSampe i need to delete job definition, only one delete. But i only need distinct activations_id. You think there is easy way i can get this value out of those triples in  jobs_to_clean ? It can be another loop, not part of COS cleanup

**Comment by JosepSampe** [comment]
@gilv just to clarify: previously, array-jobs had one job-definition for each element of the array, i.e. 1000 element in array = 1000 job-definitions in code engine. And now we  already support array-jobs, i.e. 1000 element in the array = 1 job-definition in code engine. Am I right?

**Comment by gilv** [comment]
@JosepSampe i wrote nonsense in previous comment ;) It's one job definition per many invocations. I will fix it

**Comment by gilv** [comment]
@JosepSampe resolved in commit 5a2aa89b5941048bb7f0ff045005143603d530d8. No more COS bombs ;)
