### ISSUE TITLE
REMOTE_INVOKER_MEMORY = 2048 should be configurable

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#381]
REMOTE_INVOKER_MEMORY = 2048 in the invoker should be configurable. Not all the backend engine need REMOTE_INVOKER_MEMORY. I suggest if REMOTE_INVOKER_MEMORY is not configured, then the value will be the same as user provide in runtime_memory. 

@JosepSampe what do you think?

**Comment by JosepSampe** [comment]
IMO, it is not necessary to be configurable.
Which backends does not need REMOTE_INVOKER_MEMORY? and for what reason do you want to make it configurable?

Remote invoker is a special feature only for serverless backends. When a user is located in a poor network, he can use this feature that uses a single cloud function to invoke the map(). This substantially reduce the invocation time. 
After tens of tests, the memory that better fits in terms of performance ant time is 2048. If you put less memory, the invocation of the map() will take alot of time (like if the feature was not activated). If you pout more memory there is no benefit in contrast of 2048. So the memory that better fits here is 2048.

**Comment by gilv** [comment]
@JosepSampe as you advised, i am using code engine with remote_invoker. But i don't need REMOTE_INVOKER_MEMORY at all there, i need the same memory as was provided by the user for invocation memory

**Comment by JosepSampe** [comment]
@gilv The job_definition that is sent to the invoke() contains the memory you actually need. I think you already find it ;)

**Comment by gilv** [comment]
👍
