### ISSUE TITLE
Documentation with new backends design

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#382]
@JosepSampe I guess now there is need to update documentation, based on this discussion, right?

@gilv It is all easy to understand if you think that now lithops supports 3 modes of execution: localhost, serverless and standalone. Each mode of execution has its own Executor with its own parameters. Form example, servelss executor has runtime_memory parameter, while StandaloneExecutor has cpu, memory, instances, etc parameters, while LocalhostExecutor has none of them. That is why we have 3 executors. They share 99% of code, what only changes is the __init__ method and its parameters.
This way, in your scripts you can differentiate what is executed in serverless, in a VM or in localhost:

...
fexec = lithops.ServrelessExecutor()
...
fexec = lithops.StandaloneExecutor()
...
fexec = lithops.LocalhostExecutor()
...
Then we have another executor called FunctionExecutor. The FunctionExecutor is a top-level executor that engloves the localhost, servereless and standalone executors. So instead of using in your scripts the low-level executors stated before, you can use everywhere the FunctionExecutor and then decide in config if they are serverless, localhost or standalone. For example:

...
fexec = lithops.FunctionExecutor(type='serverless') #type param is loaded from config file if not provided
...
fexec = lithops.FunctionExecutor(type='localhost')
...
fexec = lithops.FunctionExecutor(type='standalone')
...
Docker backend and Local backend was merged into the new Localhost mode of execution because in fact docker and localhost were not compute backends, but execution environaments. This reduced alot the complexity of the code.

Now you can run function in your default python3 interpreter by:

fexec = lithops.LocalhostExecutor()
Also, you can run functions in a docker image by simply specifying a docker runtime:

fexec = lithops.LocalhostExecutor(runtime='jsampe/lithops-py3.6')
With this, in the future we can also support virtualenvs packaged into a zip file, so a user could specify something like this to run functions within a packaged viertualenv:

fexec = lithops.LocalhostExecutor(runtime='my-lithops-env-py36.zip')
LocalhostExecutor is only localhost executor and can only run local jobs. Anything remote like a regular VM is StandaloneExecutor(), which includes all the ssh logic needed to interact with the VM.

With the standalone executor you can also do this:

fexec = lithops.StandaloneExecutor()  # will run functions in the default python3 interpreter of the VM
...
fexec = lithops.StandaloneExecutor(runtime='jsampe/lithops-py3.6') # will run functions in a docker container
All of this will be properly documented, but for now I don't want to modify any other file ;)

**Comment by JosepSampe** [comment]
@gilv WIP ;)

**Comment by gilv** [comment]
@JosepSampe another point..i think current documentation very confusing with respect to runtimes.We need a doc page or may be mention it somewhere what compute engine and what is default runtime. This way, every time we release new version, we perhaps update the runtime. Otherwise i feel, all the default runtimes are not updated and we don't have a single list of default runtimes

**Comment by gilv** [comment]
@JosepSampe is this suppose to work like this?

         pw = lithops.ServrelessExecutor(log_level='DEBUG', runtime = lithops_runtime, runtime_memory="256")

if yes, then it's not regular naming for functions, but class and looks less good.
i guess it better be

     pw = lithops.servreless_executor(log_level='DEBUG', runtime = lithops_runtime, runtime_memory="256")

no?

Anyway, it fails AttributeError: module 'lithops' has no attribute 'ServrelessExecutor'

**Comment by gilv** [comment]
@JosepSampe in addition to comment above, i also tried

          pw = lithops.function_executor(type='code_engine', log_level='DEBUG', runtime = lithops_runtime, runtime_memory="256") 


Got 

2020-10-19 14:09:35,465 [INFO] lithops.config: Lithops v2.2.0-SNAPSHOT
2020-10-19 14:09:35,465 [DEBUG] lithops.config: Loading configuration
2020-10-19 14:09:35,465 [INFO] lithops.config: Getting configuration from /Users/gilv/Dev/lithops/default_config.yaml
2020-10-19 14:09:35,534 [DEBUG] lithops.config: Loading Storage backend module: ibm_cos
2020-10-19 14:09:35,632 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2020-10-19 14:09:35,632 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
2020-10-19 14:09:35,632 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
2020-10-19 14:09:35,679 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2020-10-19 14:09:35,679 [INFO] lithops.executors: Code_engine Executor created with ID: 08e1c0/0
Traceback (most recent call last):
  File "/Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/PyWrenColigoTest.py", line 25, in <module>
    futures = pw.map(my_map_function, iterdata)
  File "/Users/gilv/Dev/lithops/lithops/executors.py", line 196, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
AttributeError: 'FunctionExecutor' object has no attribute 'invoker'

**Comment by JosepSampe** [comment]
The correct usage ia to use directly the class.
Methods are used when you have to wrap the class with some logic. For example ibm_cf_executor() has some minor internal logic. In any other case it is preferable to use the class. 

Try installing again the project to fix errors

**Comment by gilv** [comment]
@JosepSampe I think function_executor to me is the best one...very generic and the simpler to use. I guess it has some bugs now so it fails for me

**Comment by JosepSampe** [comment]
> The correct usage is to use directly the class.
> Methods are used when you have to wrap the class with some logic. For example ibm_cf_executor() has some minor internal logic.
> In any other case it is preferable to use the class.
> 
> Try installing again the project to fix import errors

**Comment by JosepSampe** [comment]
> @JosepSampe in addition to comment above, i also tried
> 
> ```
>       pw = lithops.function_executor(type='code_engine', log_level='DEBUG', runtime = lithops_runtime, runtime_memory="256") 
> ```
> 
> Got
> 
> 2020-10-19 14:09:35,465 [INFO] lithops.config: Lithops v2.2.0-SNAPSHOT
> 2020-10-19 14:09:35,465 [DEBUG] lithops.config: Loading configuration
> 2020-10-19 14:09:35,465 [INFO] lithops.config: Getting configuration from /Users/gilv/Dev/lithops/default_config.yaml
> 2020-10-19 14:09:35,534 [DEBUG] lithops.config: Loading Storage backend module: ibm_cos
> 2020-10-19 14:09:35,632 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
> 2020-10-19 14:09:35,632 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
> 2020-10-19 14:09:35,632 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
> 2020-10-19 14:09:35,679 [DEBUG] lithops.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
> 2020-10-19 14:09:35,679 [INFO] lithops.executors: Code_engine Executor created with ID: 08e1c0/0
> Traceback (most recent call last):
> File "/Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/PyWrenColigoTest.py", line 25, in
> futures = pw.map(my_map_function, iterdata)
> File "/Users/gilv/Dev/lithops/lithops/executors.py", line 196, in map
> runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
> AttributeError: 'FunctionExecutor' object has no attribute 'invoker'

You have an error in the call.
The parameter type is one of (serverless, standalone, localhost), not code_engine. code_engine is the backend, so your correct line is:
```
pw = lithops.FunctionExecutor(backend='code_engine', log_level='DEBUG', runtime=lithops_runtime, runtime_memory=256)
```

**Comment by gilv** [comment]
@JosepSampe 

ef function_executor(type=None, config=None, runtime=None, runtime_memory=None,
                      workers=None, compute_backend=None,
                      storage_backend=None, rabbitmq_monitor=None,
                      remote_invoker=None, log_level=None):
 
it's compute_backend right now...i guess need to be changed

**Comment by JosepSampe** [comment]
> @JosepSampe I think function_executor to me is the best one...very generic and the simpler to use. I guess it has some bugs now so it fails for me

Yes, the intention is to promote the usage of lithops.FunctionExecutor() and deprecate all the super fine-grain executors (ibm_cf_executor, knative_executor, clodrun_executor, etc etc). This way we can reduce alot of duplicated code in the __init__ file of the project

**Comment by JosepSampe** [comment]
> @JosepSampe
> 
> ```
> def function_executor(type=None, config=None, runtime=None, runtime_memory=None,
>                       workers=None, compute_backend=None,
>                       storage_backend=None, rabbitmq_monitor=None,
>                       remote_invoker=None, log_level=None):
> ```
> 
> it's compute_backend right now...i guess need to be changed

Use directly the class ;)

**Comment by gilv** [comment]
@JosepSampe but class looks ugly in Python...in Python we call functions, not really classes.
I prefer lithops.function_executor and not lithops.FunctionExecutor()... we are Python, not Java ;)

**Comment by gilv** [comment]
@JosepSampe this one works fine

    pw = lithops.function_executor(type = "serverless", compute_backend='code_engine', log_level='DEBUG', runtime = lithops_runtime, runtime_memory="256")

**Comment by JosepSampe** [comment]
> @JosepSampe but class looks ugly in Python...in Python we call functions, not really classes.
> I prefer lithops.function_executor and not lithops.FunctionExecutor()... we are Python, not Java ;)

In Python we call classes everywhere when you want to create an instance of something that contains methods. In our case an **executor** ;)
https://github.com/apache/ignite/blob/master/examples/redis/redis-example.py#L23
https://github.com/spark-jobserver/python-sjsclient#getting-started
etc
etc

**Comment by gilv** [comment]
@JosepSampe yeah...may be it's me old fashioned, i don't know..just personally i like to provide API in Python without two much classes. But i don't mind

**Comment by JosepSampe** [comment]
You are used to using methods in lithops to create executors, but the correct way is to use directly the class. If `function_executor()` method had some internal login before creating the class, then it make sense to use a method, but in our case there is no additional logic in `function_executor()` method, it is simply a wrapper of the class, i.e, not needed code ;)
