### ISSUE TITLE
config_template.yaml is not updated

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#383]
@JosepSampe :)

**Comment by gilv** [comment]
@JosepSampe by the way, where are keys with retry, for example:

    retry_sleeps: [1, 20, 40, 60, 120]
    retries: 5

**Comment by gilv** [comment]
@JosepSampe another point, regarding ibm-vpc:
previous configuration had in Docker section.

    ssh_user: aaa
    ssh_key_filename: <PATH>/.ssh/id_rsa.pub

where it suppose to go now? into ibm_vpc or into standalone ?

**Comment by gilv** [comment]
@JosepSampe another one :)

where is 

include_modules: ["ABC"]

should go?

**Comment by JosepSampe** [comment]
> @JosepSampe another point, regarding ibm-vpc:
> previous configuration had in Docker section.
> 
> ```
> ssh_user: aaa
> ssh_key_filename: <PATH>/.ssh/id_rsa.pub
> ```
> 
> where it suppose to go now? into ibm_vpc or into standalone ?

This information is in https://github.com/lithops-cloud/lithops/blob/master/config/compute/ibm_vpc.md#summary-of-configuration-keys-for-ibm-vpc

**Comment by JosepSampe** [comment]
> @JosepSampe by the way, where are keys with retry, for example:
> 
> ```
> invocation_retry: <True/False>
> retry_sleeps: [1, 20, 40, 60, 120]
> retries: 5
> ```

These keys were deleted 1 year ago, No needed anymore

**Comment by JosepSampe** [comment]
> @JosepSampe another one :)
> 
> where is
> 
> include_modules: ["ABC"]
> 
> should go?

These keys go to lithops section. Need to update docs

**Comment by JosepSampe** [comment]
@gilv done? ;)
