### ISSUE TITLE
JobMonitor._job_monitoring_os can become stuck polling forever

### ISSUE THREAD

**Issue by LachlanStuart** [lithops-cloud/lithops#395]
I'm investigating a weird imbalance in my billing when using Lithops with IBM CF/COS. Somehow I got 5x as many "Class A" COS requests (PUT, POST, LIST) vs "Class B" requests (GET, DELETE, etc.). These Class A requests cost almost 10x as much as the rest of my total compute/storage usage.
![image](https://user-images.githubusercontent.com/26366936/96900920-e97d0f00-1492-11eb-9a6e-2c46d306d962.png)

In normal Lithops operation, I'd expect every PUT/POST to also have a matching GET, so my suspicion is that there are too many LISTs happening. I think I've found an explanation:

With certain types of errors, it seems `JobMonitor._job_monitoring_os` will continue running forever. It calls `list_keys` (a "Class A" API call in IBM Cloud) 3 times per second, costing about US$1 every 18 hours. However, it can get even worse - if a new `FunctionExecutor` is used for each job, it's possible to cause multiple simultaneous broken monitors. The monitors never stop, even if the `ServerlessInvoker` is stopped and the `FunctionExecutor` is garbage collected. This could become very expensive if Lithops is run from some sort of service that rarely restarts (e.g. a web API). In my case, I left my development Python console running overnight after a number of runs that had errors.

After adding logging to `JobMonitor._job_monitoring_os`, I've found at least three scenarios that cause it to get stuck:
* If execution is interrupted by a `KeyboardInterrupt`
* If a job fails while there are still other unstarted jobs, FunctionExecutor will clean up the status files for the jobs that did run, which causes `total_callids_done_in_job` to actually decrease back to 0.
* If the openwhisk client gets a 404 response when invoking a serverless function (in my case it tried to start a runtime that never existed - I'm still investigating how this happened)

My main concern is not the error that allowed this to happen, but the potential for this to cause massive bills without any explanation. It would be nice to see some sort of failsafe so that `_job_monitoring_os` eventually stops, even if the jobs don't fail correctly.

Lithops version: 2.2.0
Lithops config: 
```
    "lithops": {
      "storage_bucket": "metaspace-ls-de2",
      "storage_backend": "ibm_cos",
      "executor": "serverless",
      "include_modules": ["engine/sm"],
      "data_cleaner": true,
      "data_limit": false,
      "workers": 1000
    },
    "serverless": {
      "backend": "ibm_cf",
      "runtime": "lachlanstuart/metaspace-annotation3.8.5:1.8.0",
      "runtime_timeout": 600
    },
```

**Comment by JosepSampe** [comment]
@LachlanStuart Just to put me in context: Based on your described scenarios, and with the fact that the `JobMonitor._job_monitoring_os` is set as a `daemonic` thread (that is abruptly stopped when the script finishes in case you ran it from a terminal), are you experienced it from a notebook? or did you experience the same from a terminal?

**Comment by JosepSampe** [comment]
I added a stop flag in #394 that stops the JobMonitor in the same way that the invoker is stopped. So scenario 1 and 2 should be fixed

**Comment by LachlanStuart** [comment]
> are you experiencing it from a notebook?

For development I'm running from the PyCharm Python Console. I can run the job many times in the same Python process, and the process only exits when I click the stop button or quit PyCharm. In production I will be running these jobs from a web server that will usually run in the same Python process for weeks or months.

> I added a stop flag in #394

Thanks! I'll pull the latest code and try it out.

**Comment by gilv** [comment]
I wonder why i never observed that it might get stuck

**Comment by LachlanStuart** [comment]
@gilv It's a background thread that doesn't have any logging. You can keep doing normal stuff in Python after an error, and you won't notice that it's still polling COS. I only realized there was a problem because my billing looked strange.

**Comment by LachlanStuart** [comment]
@JosepSampe I tested each of the scenarios:

> If execution is interrupted by a KeyboardInterrupt
:heavy_check_mark: The job monitoring stops immediately.

> If a job fails while there are still other unstarted jobs, FunctionExecutor will clean up the status files for the jobs that did run, which causes total_callids_done_in_job to actually decrease back to 0.
:heavy_check_mark: The job monitor stops after all invocations have finished.

:thinking:  Instead of immediately reraising the error, it now waits until all functions have finished executing, including starting new pending functions, and then raises the error. Not sure if this is a bug or just a behavior change.

> If the openwhisk client gets a 404 response when invoking a serverless function
:negative_squared_cross_mark: It continues to run forever, even after the execution timeout, and `executor.get_result` never returns. However, if I Ctrl+C to interrupt it, the job monitoring stops correctly. I think this is a separate bug - I'll keep investigating and raise a separate issue. 

However, there's now a new bug - job monitoring doesn't reset itself when you re-use an executor, even if there hasn't been any error. Reproduction code:

```
def myfunc(i):
    pass

executor = function_executor(config=lithops_config, workers=1)

fs = executor.map(myfunc, range(3))
executor.get_result(fs)

fs = executor.map(myfunc, range(3))
executor.get_result(fs) # This never returns because invocations 2 & 3 are never started
```

[Output logs](https://gist.github.com/LachlanStuart/ade2897834f5c63e335f363419c332a1). Note that I added `_job_monitoring_os loop` and `_job_monitoring_os exit loop` debug logs - it seems the second instance immediately stopped because `self.should_run` was already `False`

**Comment by JosepSampe** [comment]
Thanks for the report @LachlanStuart. I'm going to investigate it

**Comment by JosepSampe** [comment]
I have a fix, Now stop flag is per `execution_id+job_id` instead of global. I'm testing all possible cases

**Comment by JosepSampe** [comment]
@LachlanStuart Added a fix in #400 . ready to test

**Comment by LachlanStuart** [comment]
I re-tested each of the scenarios, as well as my metabolomics code. The Job Monitor seems to stop correctly now when there are errors, and it has gone back to the expected behavior of not launching new jobs after an error has been detected.

@JosepSampe Thanks for the quick fix!

**Comment by JosepSampe** [comment]
@LachlanStuart thanks to you for your awesome reports and feedback
