### ISSUE TITLE
requirements.txt is python version related

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#401]
While we deploy runtimes for different Python versions, requirement.txt remains static with specific package versions.
Some dependencies need specific versions for different Python versions and thus requirements.txt need to be updated all the time based on Python version we plan to use.

Not sure what is best approach to resolve this

@JosepSampe any thoughts?

**Comment by gilv** [comment]
@JosepSampe I assume the correct approach is to reduce number of Docker files we have, for example ibm_cf has too much and then have different requirements.txt per Docker file per Python version?

**Comment by gilv** [comment]
@JosepSampe I know it's wrong what i did...see this commit 96471985bd976721ba82236a3a9203c213c74f99.
The requirements38.txt is what needed for Python 3.8.5.
And Dockerfile.python385 is unclear why Dockerfile.python38 is different.

We need somehow find a way to limit number of images and have requirements per Python version

**Comment by JosepSampe** [comment]
I think we can delete all pined versions from all packages in requirements.txt as we already did in setup.py, since the only strong requirement we have is pika==0.13.1. This way each python version will install its appropriate package versions, and we will not have any other issue in the future due to an old package version.

**Comment by gilv** [comment]
@JosepSampe how it will work with setup.py? For example Python 3.8.5 need 
```
gevent == 20.9.0
flask == 1.1.1
```
also numpy and some other packages.

while Python 3.7.5 need older versions.

**Comment by JosepSampe** [comment]
I think each python version installs the appropriate package versions. So if you build a docker with python 3.8, it will automatically install gevent 20.9.0, and if you build  a docker with python.3.7, it will install the appropriate version if 20.9.0 is not compatible.

**Comment by gilv** [comment]
@JosepSampeI had hard time with EMBL moving to 3.8.5...need specific packages for 3.8.5 and then 3.7.5 didn't worked anymore. So we need manually specify packages for different Python versions
