### ISSUE TITLE
Testing Gen2 VM with most recent code

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#402]
I open this to track how Lithops-Gen2 integration works. I am using most recent code.  i created new Ubuntu 20 based VM then deployed "standalone" executer. Everything was installed automatically on VM and workload completed like a charm :)
I didn't had to install anything manually in VM, like docker, etc.

I do see that VM remained started and didn't got shutdown. Seems @kpavel observe the same.
We try to figure out if it matter of configuration or something is not works properly with dismantle and VM shutdown.

@JosepSampe FYI

**Comment by JosepSampe** [comment]
Do you see messages like this in /tmp/lithops/proxy.log?
```
2020-10-26 11:21:02.178 INFO proxy - budget_keeper: Time to dismantle: 275 seconds
```

Or they don't appear?

**Comment by gilv** [comment]
@JosepSampe VM did stopped by itself after some time. I see it now. Do we call shutdown once the Lithops job completed or it always auto_dismantle after some time?

**Comment by JosepSampe** [comment]
If you have `auto_dismante = True` VM will shutdown after soft_dismantle_timeout (5 minutes). If you have `auto_dismantle=False` VM shutdowns after `hard_dismantle timeout` (1 hour) as long as you didn't called `exec.dismantle()` before.

**Comment by gilv** [comment]
well...all works like a charm for me :) And seems @kpavel also satisfied...
@JosepSampe thanks a lot.
