### ISSUE TITLE
Ibm vpc backend hangs forever on the "Waiting Lithops proxy to become ready"

### ISSUE THREAD

**Issue by kpavel** [lithops-cloud/lithops#403]
If new ibm vpc VM instance is used, while keeping same runtime name in .lithops_config the map job will hang forever on  Waiting Lithops proxy to become ready. Reason - it assumes the vm already has runtime preinstalled while it doesn't.
Easy solution - validation that runtime is there directly using ssh instead from cache/db

**Comment by JosepSampe** [comment]
@kpavel good finding. Thanks. I think this is caused because you used same IP for different VM. 
I think its even easier to fix by modifying get_runtime_key() method and use instance_id instead of ip_address.
