### ISSUE TITLE
Warning installing lithops master branch

### ISSUE THREAD

**Issue by JosepSampe** [lithops-cloud/lithops#415]
Each time I install master branch lithops i get this warning:

/usr/lib/python3/dist-packages/setuptools/dist.py:485: UserWarning: The version specified ('2.2.3-SNAPSHOT') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

@gilv I think we should name master branch version with something like: `2.2.3dev0` (I saw it in another project). What do you think?

**Comment by gilv** [comment]
@JosepSampe i never saw such warning...you see it with pip install -U . ?

**Comment by JosepSampe** [comment]
@gilv I see it with `python setu.py install`

**Comment by JosepSampe** [comment]
@gilv According to python specifications, development releases are in the form of X.Y.devN. https://www.python.org/dev/peps/pep-0440/#developmental-releases

Currently in our case, looks like  master branch should be 2.2.dev3 instead of 2.2.3-SNAPSHOT, according to python PEP

**Comment by gilv** [comment]
@JosepSampe sure, nobody can argue with the spec :) Let's change it as you propose

**Comment by JosepSampe** [comment]
Changed in #416
