### ISSUE TITLE
Memory limits in standalone executors

### ISSUE THREAD

**Issue by LachlanStuart** [lithops-cloud/lithops#436]
Currently, standalone runners simultaneously run all received jobs at once, ignoring the `runtime_memory` parameter. This can cause activations to run out of memory if too many activations are run in parallel through a `map` call. The `workers` config setting can be used to limit the number of parallel activations started by a `FunctionExecutor`, but there are two drawbacks - it can't be dynamically changed for each function (unless you modify `executor.config` directly, which feels like a bad idea), and it doesn't prevent overallocation when multiple `FunctionExecutor`s are running against the same VPC instance.

It would be nice if standalone executor's "proxy" server managed the number of incoming activations to prevent resource overload. Preventing memory overallocation is the most important, because OOMs cause activations to completely fail. It would also be nice if parallelism was limited so that there weren't more activations than CPU cores, because CPU contention can reduce throughput.

There are a couple related ideas I had around memory management in VPCs that may be worth considering:
* Setting [memory limits](https://docs.docker.com/config/containers/resource_constraints/) for each container in Docker so that the correct process is killed on OOM (instead of the kernel deciding which process to kill), and so that it's easier to find which function has its `runtime_memory` set too low.
* Adding instructions for setting up a swapfile in IBM VPCs so that OOMs are less frequent. I followed [these instructions](https://github.com/lithops-cloud/lithops/blob/master/config/compute/ibm_vpc.md) to make a 32GB Ubuntu instance, but it seems the image has no swapfile by default.

I don't have an urgent need for this, but I have several upcoming use-cases that would benefit from it:
* I would like to run multiple instances of our pipeline in parallel. This means there will frequently be requests from multiple executors to use the VPC runner at the same time. Fortunately everything will run from one process, so I can use a mutex as a workaround.
* I would like to experiment with automatically determining the memory each function needs based on properties about its input data. When the task is greater than 4GB, it'd be most efficient if I could control whether the standalone executor runs e.g. 5x6GB activations, or 3x10GB activations in parallel. This would also benefit from [declaring different memory requirements per activation](https://github.com/lithops-cloud/lithops/issues/354), as these jobs can vary in size significantly.

**Comment by gilv** [comment]
@kpavel can you check this please?

**Comment by kpavel** [comment]
@LachlanStuart I think we can achieve it by presenting a sliding window of active jobs inside the VPC with FIFO queue of jobs inside proxy.py. At naive approach, window size will be derived from the amount of memory initially available on the machine and expected job size specified by the executor.
Later, the algorithm can be improved to dynamically watching the currently available resources including CPU.

Regarding limiting docker container with max memory:  i think in most usecases, we would like all of the jobs to be completed successfully. Maybe better to maintain sliding window of the running jobs, which in case we detect failing job, instead of failing whole execution put this job back to queue and dynamically decrease the size of the window. Then rerun those that failed.

**Comment by gilv** [comment]
@LachlanStuart what do you think on the proposal from @kpavel ?

**Comment by LachlanStuart** [comment]
@kpavel The FIFO queue / sliding window approach sounds great, as long as I can control it per-job.

> in case we detect failing job, instead of failing whole execution put this job back to queue and dynamically decrease the size of the window. Then rerun those that failed.

Were you thinking about implementing this in the in the Standalone proxy, or in the executor? If it's just for Standalone, I don't think this is needed - I haven't encountered a real-world case of unexpected OOMs (except for the "all jobs at once" issue) in Standalone as there's so much extra memory. However, if it was in the executor, where it would be shared with the Serverless code, then this would be AWESOME. I've had a lot of trouble with OOMs in Serverless, as the memory limits are much lower.

> Regarding limiting docker container with max memory: I think in most usecases, we would like all of the jobs to be completed successfully. 

That's a good point. I suggested this just so that behavior would be consistent between Serverless and Standalone so that it's easier to switch between them, but if it's possible for both to avoid OOMs with retry logic, that would be a much better approach.

**Comment by gilv** [comment]
@LachlanStuart if we run many executors from different clients, then we can't use executor to keep queue...unless we have some 3rd party external queue to maintain jobs... or keep it in proxy. I think we need queue only for VPC and in this case we can keep queue inside proxy.
regarding serverless, very soon we have production IBM Code Engine (it's beta now). Lithops supports it, so from your experience it's 0 change of the code, but IBM Code Engine supports up to 32GB of memory and no limit on time...so you will never hit OOM again with Code Engine

**Comment by gilv** [comment]
@kpavel ^^^

**Comment by LachlanStuart** [comment]
> if we run many executors from different clients, then we can't use executor to keep queue...

@gilv I was only suggesting using the executor for the retry-after-OOM logic. I agree that it would be best to handle queueing and the sliding window in the proxy.

**Comment by JosepSampe** [comment]
@sergii-mamedov FYI. Currently (2.5.0), Lithops already implements a job queue in the master/proxy VM, so if multiple Lithops instances submits jobs to the same VM, now they won't run at the same time, but one after another.

**Comment by sergii-mamedov** [comment]
I think you can close this issue "as fixed"
