### ISSUE TITLE
cloudrun deployment

### ISSUE THREAD

**Issue by otrack** [lithops-cloud/lithops#445]
It seems that there are several issues with the deployment over GCP cloudrun. The version used was gcloud SDK 318 and commit ac65e8315fb6349167104c0c9ed194804635229 for lithops.

The command "lithops runtime build -f runtime/cloudrun/Dockerfile.python37 login/img" fails with "COPY failed: stat /var/lib/docker/tmp/docker-builder224709891/lithops_cloudrun.zip: no such file or directory". This makes fully sense since the build happens inside a container in GCP which does not contain a copy of lithops. 

Simply building the image locally sidesteps the above  issue. However, one hits another problem when running a test file, say, example/call_async.py, "raise Exception('There was an error creating the service')". This second issue is with the naming of the service and invoking " gcloud run deploy [..]" returns "Invalid service name [python3.8--256m]. Service name must use only lowercase alphanumeric characters and dashes. Cannot begin or end with a dash, and cannot be longer than 63 characters". The use of a the double dash is the service name is not legal.

I strongly suggest to have unit tests to catch these bugs and strengthens the various scenarios of usage.

**Comment by JosepSampe** [comment]
Fixed in #552
