### ISSUE TITLE
'JobRunner' object has no attribute 'executor_id'

### ISSUE THREAD

**Issue by gfinol** [lithops-cloud/lithops#456]
Using Lithops on version 2.2.7 I got the following error:

```
Traceback (most recent call last):
  File "/action/lithops/worker/jobrunner.py", line 255, in run
  File "/action/lithops/worker/jobrunner.py", line 100, in _save_modules
AttributeError: 'JobRunner' object has no attribute 'executor_id'
```

Apparently the attribute `executor_id` was remove in 433eae7. But in line  [100](
https://github.com/lithops-cloud/lithops/blob/433eae7a5bd7132424473a5ef73e362127a41295/lithops/worker/jobrunner.py#L100) it is still been used.

**Comment by JosepSampe** [comment]
That line should have been deleted by mistake. I reverted it in master branch
