### ISSUE TITLE
Please describe example how Pool is initialised with a concrete serverless backend

### ISSUE THREAD

**Issue by rmey** [lithops-cloud/lithops#467]
There is no example on how to use the pool API with a concrete backend.

**Comment by rmey** [comment]
How do I specify for pool a serverless backend?
`# from multiprocessing import Pool
from lithops.multiprocessing import Pool
import random


def is_inside(n):
    count = 0
    for i in range(n):
        x = random.random()
        y = random.random()
        if x*x + y*y < 1:
            count += 1
    return count


if __name__ == '__main__':
    np, n = 96, 15000000000
    part_count = [int(n/np)] * np
    pool = Pool(processes=np, initargs={'runtime_memory': 4096})
    count = pool.map(is_inside, part_count)
    pi = sum(count)/n*4
    print("Esitmated Pi: {}".format(pi))`

**Comment by rmey** [comment]
OK I tried this now which seems to work:
`pool = Pool(processes=np, initargs={'runtime_memory': 1024, 'mode':'serverless','backend':'code_engine','runtime':'ibmfunctions/lithops-ce-3.8.5-2.2.9:1.0.0'})
    `

**Comment by gilv** [comment]
@JosepSampe does it documented somewhere else?  or the usage of Pool is  a missing part that need to be added?

**Comment by JosepSampe** [comment]
@gilv Docs of `multiprocessing` are in progress. We will submit them soon.

In any case, apart of using `initargs`, a concrete backend can be also set in config as usual, in `serverless` section: https://github.com/lithops-cloud/lithops/blob/master/config/compute/code_engine.md#edit-your-lithops-config-and-add-the-following-keys-1

**Comment by JosepSampe** [comment]
Docs added in #473
