### ISSUE TITLE
Supporting other container registry, not just Docker

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#471]
There are various container registries available, users may have private ones, IBM container registry, etc. 
Lithops should support them as well, not just Docker registry.

**Comment by gilv** [comment]
@JosepSampe what do you think on this?

**Comment by JosepSampe** [comment]
@gilv Theoretically, lithops is not pinned to any container registry, so you should be able to use all them. 
In fact Google cloud run uses the google container registry
