### ISSUE TITLE
Cloudpickle not working as expected with python >= 3.8

### ISSUE THREAD

**Issue by kpavel** [lithops-cloud/lithops#475]
Recently Cloudpickle 1.6 been added and it is used by default when python version is >= 3.8

https://github.com/lithops-cloud/lithops/blob/master/lithops/libs/cloudpickle/__init__.py

The problem is that it doesn't produce modules dependencies. I suggest we roll back to previous cloudpickle version for python >=3.8 as well, as long as the issue not resolved.

**Comment by JosepSampe** [comment]
@kpavel This is commonly due the project structure you have.  I just run some examples with with Python3.8 and in my case the deps are correctly pickled and transferred. But I use basic project structure. Can you provided a specific example to reproduce the issue?

**Comment by kpavel** [comment]
@JosepSampe Just run something with dependency not prepackaged in the runtime.
e.g. 
```
#!/usr/bin/python

import lithops
import couchdb

def hello2(name):
    couch = couchdb.Server('http://10.97.83.39:5984')
    version = couch.version()

    print("couchdb_version", version)
    return 'Hello2 {}!'.format(version)

fexec = lithops.FunctionExecutor()
fexec.call_async(hello2, 'World')
print(fexec.get_result())
```

**Comment by JosepSampe** [comment]
@kpavel hmm, very weird, I will investigate it. If instead you use the next code it works:

```python
import lithops
from couchdb import Server


def hello2(name):
    couch = Server('http://10.97.83.39:5984')
    version = couch.version()

    print("couchdb_version", version)
    return 'Hello2 {}!'.format(version)

fexec = lithops.FunctionExecutor(log_level='DEBUG')
fexec.call_async(hello2, 'World')
print(fexec.get_result())
```

**Comment by JosepSampe** [comment]
I found a fix, need to be tested but I will submit it soon
