### ISSUE TITLE
Too much log output

### ISSUE THREAD

**Issue by LachlanStuart** [lithops-cloud/lithops#477]
The output during execution of a Lithops function can be quite spammy, and is impossible to turn off. This is a problem in application logs, as a pipeline with 10+ Lithops calls that sometimes invoke 1000s of activations, it can result in tens of thousands of lines of logs.

There are several issues:
* The current behavior [detects if logging is disabled and `print` instead](https://github.com/lithops-cloud/lithops/blob/master/lithops/invokers.py#L149-L153) in some places. This makes it hard to completely turn off logging when it's unwanted.
* Too much is logged at `INFO` level, including [one line for every activation](https://github.com/lithops-cloud/lithops/blob/master/lithops/invokers.py#L298-L299). The one-time messages such as creating new runtimes are fine, but the messages that happen every job are a problem.
* When an activation fails, it doesn't seem like the Activation ID is ever logged. It looks like [there's code that tries to print it if the exception is never handled](https://github.com/lithops-cloud/lithops/blob/master/lithops/future.py#L188-L203), but it doesn't help in situations where exceptions are caught and logged
* tqdm output looks awful when an application's stdout is piped to file (e.g. when running as a system service or through `supervisor`) [example](https://gist.github.com/LachlanStuart/1cf2355524860170e9ce399251d2fdd8)

My suggestions:
* Completely remove the `print` fallback and only use `logging`. Using `logging` has the advantage that the user can override the log level on a per-module basis.
    Am I right in thinking that the `print` fallback was to make sure that new users can see the messages without having to configure anything (because Python hides INFO by default)? If so, this behavior seems reasonable as a default, but it should be disableable. I would suggest making a `log_level` Lithops config setting with this behavior:
    * If the user sets it to `null`/`None`, don't make any changes to logging behavior
    * If the user sets it to `INFO`/`WARNING`/etc. configure the `lithops` root logger to that level
    * If no value is specified and the logger is in the default level of `WARNING`, configure the `lithops` root logger to the `INFO` level
* Review the `INFO`-level messages that are logged in `executor.map` and `executor.get_result` calls, and downgrade them to `DEBUG` level if they're not needed. Ideally there would be maximum 2-3 `INFO`-level log messages per job. 
* When a failed activation is detected, I have several ideas:
    * The easiest is to just log its activation ID at `WARNING` level in the [`throw_except`](https://github.com/lithops-cloud/lithops/blob/master/lithops/future.py#L188-L203) code-path before calling `reraise`. 
    * If you're concerned people may design functions that intentionally raise exceptions for the host to handle and might not want the log messages, you could either put them in their own logger e.g. `lithops.future.exceptions`, or you could override the traceback when calling `reraise` so a custom exception message including the activation details appears in the "During handling of the above exception, another exception occurred" chain when the exception is logged
* With tqdm, if you specify `disable=None` instead of `disable=False`, it will be disabled in non-TTY (i.e. non-interactive) environments.

**Comment by JosepSampe** [comment]
> Am I right in thinking that the print fallback was to make sure that new users can see the messages without having to configure anything (because Python hides INFO by default)? 

Yes, this is the main reason of `prints`. But those prints were added at the very beginning of the project when we had no logging. Now we have logging everywhere so we can address your suggestions:
- If the user sets it to null/None, don't make any changes to logging behavior
- If the user sets it to INFO/WARNING/etc. configure the lithops root logger to that level
- If no value is specified and the logger is in the default level of WARNING, configure the lithops root logger to the INFO level

What do you think @gilv ?

**Comment by gilv** [comment]
@JosepSampe and in addition we remove all "prints" and follow other @LachlanStuart suggestions?

**Comment by JosepSampe** [comment]
@gilv Yes, I already already addressed some of them in #478. Just wanted to now what do you think about to remove prints and set INFO as default logging?

**Comment by gilv** [comment]
@JosepSampe sure...whatever @LachlanStuart propose i am good with :)
