### ISSUE TITLE
Wrong IBM COS endpoint used in Standalone/IBM VPC

### ISSUE THREAD

**Issue by LachlanStuart** [lithops-cloud/lithops#480]
In the [runner.log file](https://gist.github.com/LachlanStuart/a97efcbab8e8bc191cf381baefaf4675) file on the VPC it shows a ConnectTimeoutError accessing https://s3.private.eu-de.cloud-object-storage.appdomain.cloud/metaspace-ls-de2/lithops.jobs/cf402c-1-M000/00000/status.json . On the host computer, it just looks like `executor.get_results` has stalled.

I also tried using curl from the VPC to download the URL, which also stalled. However, curl succeeded if I removed `.private` from the URL.

I don't get this error on Lithops 2.2.5, but I do get it on 2.2.10 and 2.2.11. I'm not sure why - maybe Lithops 2.2.5 used the public endpoint? 

I think that [VPCs should use the "direct" endpoint](https://cloud.ibm.com/docs/vpc?topic=vpc-connecting-vpc-cos), e.g. https://s3.direct.eu-de.cloud-object-storage.appdomain.cloud/metaspace-ls-de2/lithops.jobs/cf402c-1-M000/00000/status.json . Curl also succeeded when I tried this URL.

**Comment by JosepSampe** [comment]
@LachlanStuart IBM COS private endpoint does not work from IBM VPC. To make use the correct endpoints, you have to set the `region` parameter in `ibm_cos` section and delete the endpoints. [Check this example](https://github.com/lithops-cloud/lithops/blob/master/config/storage/ibm_cos.md#option-3-ibm-iam-api-key)

**Comment by LachlanStuart** [comment]
Thanks @JosepSampe , that fixed it.

Would it be possible to include details about config and API changes in the changelog? Each time I update Lithops, it has taken quite a bit of work to get all my code/config working again.
