### ISSUE TITLE
log file of the execution is not created

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#510]
I used CF backend and run a job.
Under  `<temp_folder>/lithops/logs/` nothing was created
Also running cli - `lithops logs get ..` didn't worked

**Comment by gilv** [comment]
@JosepSampe can you see it please?

**Comment by JosepSampe** [comment]
Local logs are only created in the `Standalone` and `Localhost` modes. In the `Serverless` mode you must use the backend-specific tool to see the logs. In your case you must use the `ibmcloud fn activation ...` cli command, or manually access the dashboard to view the logs.

This is stated [here](https://github.com/lithops-cloud/lithops/blob/master/docs/mode_serverless.md#lithops-serverless-execution-mode)

**Comment by JosepSampe** [comment]
Fixed in #553
