### ISSUE TITLE
[Code Engine/Knative] Need a config for invoke_pool_threads 

### ISSUE THREAD

**Issue by zhanggbj** [lithops-cloud/lithops#521]
As discussed in https://github.com/lithops-cloud/lithops/issues/448, current **invoke_pool_threads= 500** is a limitation for Code Engine or Knative serving, as user cannot issue 1000 POST request for 1000 execution and this will impact the lithops result. 

It would be good to have such a config in the configuration file. Thanks!

@JosepSampe @gilv

**Comment by JosepSampe** [comment]
@zhanggbj You can already set `invoke_pool_threads` in configuration, in the knative section. 

```yaml
knative:
    invoke_pool_threads: 1000
```

Note that by default in knative `invoke_pool_threads = workers`, so if you set `workers` to 1000 you will have `invoke_pool_threads` automatically set to 1000.
