### ISSUE TITLE
Lithops logo with transparent background and white font

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#543]
We need to add additional logo image with transparent background and white font to `docs/images` folder. This can be used in presentations where background is not white

**Comment by JosepSampe** [comment]
@gilv white cloud? or transparent cloud?

**Comment by gilv** [comment]
@JosepSampe transparent background and white font of the words..so it can be used in presentations with dark background

**Comment by JosepSampe** [comment]
@gilv I added 2 new logos in #547. One with the background of the cloud in white, and another with the background of the cloud transparent

**Comment by gilv** [comment]
@JosepSampe great..thanks a lot
