### ISSUE TITLE
execution_timeout and runtime_timeout

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#551]
I think both keys are not consistent. Why not to merge them into a single key? Otherwise there in `execution_timeout` in lithops section and `runtime_timeout` in serverless section. They also have different default values, which is also confuse a bit. @JosepSampe what do you think?

**Comment by JosepSampe** [comment]
I think it is not possible to merge them. They are different things:
- `runtime_timeout` is used when a runtime is deployed to a serverless platform (only 1 time). This parameter is required for serverless platform, and it is used to abruptly kill the runtime after X seconds.
- `execution_timeout` is used by lithops to kill the execution after X seconds. In this case, lithops controls this timeout, and raises as exception when it is produced. Moreover, this timeout can be set, and it can take different different values, in each `map()` call.
