### ISSUE TITLE
Improve requirements.txt for different backends

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#566]
Currently each backend has it's own `requirements.txt` file containing all kind of dependencies. However there are many common dependencies between backends and so the same dependencies are copied across different `requirements.txt`  per backend. In some cases `requirement.txt` even identical as for `ibm_cf` and `code_engine` backend.

I suggest to create new file `shared_requirements.txt` and keep it under `runtimes` root folder. This file should contain all shared dependencies between backends. In addition if there is need for specific packages, we will keep also `requirements.txt` per backend. For example  `ibm-cos-sdk` or `ibm-vpc` which is only needed for IBM backends will be stored in `requirements.txt` under `runtimes/ibm_cf` and `runtimes/code_engine`
Lithops will use both shared_requirements.txt and  requirements.txt per specific backend when building runtime

**Comment by JosepSampe** [comment]
The problem is that requirements file must be in the same folder where you run the `lithops runitme build` command, so the build will fail if you have another requirements file in a top-level folder
