### ISSUE TITLE
Accessing the storage api during multiprocessing map

### ISSUE THREAD

**Issue by REIGNjs** [lithops-cloud/lithops#682]
Hi,

I am pretty new to Lithops and multiprocessing in python and am trying to load images from IBM COS, open them with Python Pillow and convert them to thumbnails in a map function running on IBM Cloud Code Engine. I tried to load the images first and then passing the image data to the map function, but that exceeds the 4 MB limit for the iterator data. My next attempt was to load the image in the workers, but that fails with the error message: `TypeError: cannot pickle '_thread.lock' object`. The `storage.get_object(bucket='bucket', key=cos_key, stream=True)` does not work in the map function.
Am I loading the image correctly or should I follow a completely different approach?

Here is my python code:
```python
from PIL import Image
import io
import time
from lithops import Storage
from lithops.multiprocessing import Pool


storage = Storage()


def create_thumbnail(cos_key):
    cos_file = storage.get_object(bucket='bucket', key=cos_key, stream=True)
    print("Fetching file: ", cos_key)

    size = (128, 128)

    outfile = cos_key.split("/")[-1] + ".thumbnail" + str(size)
    try:
        im = Image.open(io.BytesIO(cos_file))
        im.thumbnail(size)

        # img_byte_arr = io.BytesIO()
        # im.save(img_byte_arr, "JPEG")
        # return_tuple = (outfile, img_byte_arr)
        # return return_tuple
    except OSError:
        print("cannot create thumbnail for", cos_key)


if __name__ == '__main__':

    cos_keys = storage.list_keys(bucket='bucket', prefix='images/')
    input_files = []

    print("Creating thumbnails...")
    start_time = time.time()

    with Pool() as pool:
        output_files = pool.map(create_thumbnail, cos_keys)
        print(output_files)

    print("Time needed: " + str(time.time() - start_time))

```

**Comment by JosepSampe** [comment]
@REIGNjs Storage class is not pickable, to make it working you must move `storage = Storage()` within the function `create_thumbnail`, and create another `storage = Storage()` within the `if __name__ == '__main__':`

**Comment by REIGNjs** [comment]
Thanks, that fixed the issue. Have a nice week
