### ISSUE TITLE
`include_modules` usage

### ISSUE THREAD

**Issue by ShuxinLin** [lithops-cloud/lithops#684]
Hi,

Suppose I have a python package installed locally and I want to pickle the entire module and execute it on serverless. What is the correct way to do that? I tried this but it did not work.

```
executor = lithops.FunctionExecutor(...)
futures = executor.map(map_func, tasks, include_modules=['dqlearn'])
```
I checked logs and it is always `Uploading function and data - Total: 15.2KiB` before and after I added `include_modules=...`.

Thanks!

**Comment by JosepSampe** [comment]
Hi @ShuxinLin , `include_modules` is used for filtering detected modules by Lithops.

If you activate DEBUG logs with `ithops.FunctionExecutor(log_level='DEBUG'),` you will see a line like this:

```
2021-06-22 17:21:04,111 [DEBUG] lithops.job.serialize -- Referenced modules: /usr/lib/python3/dist-packages/colorama/ansi.py, /usr/lib/python3/dist-packages/six.py, sys, /usr/lib/python3.8/pickle.py, time, /usr/lib/python3.8/os.py, /home/josep/data/dev-workspace/lithops/lithops/lithops/storage/utils.py, /usr/lib/python3.8/base64.py, /usr/lib/python3.8/logging/__init__.py, zlib
```

Then if you write `include_modules='colorama'`, all the previous modules will be filtered and only `colorama` transferred to the cloud.

Note that to make `include_modules` working, Lithops must detect the library you want to transfer to the cloud, so you must have this library referenced/imported somewhere in your app.

**Comment by ShuxinLin** [comment]
@JosepSampe thank you. The issue is solved, previously in my `../site-packages/` dir, there is only `dqlearn-0.3.1rc1-py3.7.egg` so it is not detected. Now `dqlearn/` is installed, then it works.
