### ISSUE TITLE
RabbitMQ fails to run with error code `basic_consume() got an unexpected keyword argument 'auto_ack'`

### ISSUE THREAD

**Issue by REIGNjs** [lithops-cloud/lithops#685]
Hi,

I tried to implement rabbitmq according to the docs and my lithops configuration looks like this:

```
lithops:
    storage: ibm_cos
    storage_bucket: bucket
    mode: serverless
    monitoring: rabbitmq
    data_cleaner: True
    #workers: 50
    #data_limit: 4  # in MiB
    #execution_timeout: 1800
    #include_modules: <LIST_OF_MODULES>
    #exclude_modules: <LIST_OF_MODULES>
    #log_level: INFO
    #log_format: "%(asctime)s [%(levelname)s] %(name)s -- %(message)s"
    #log_stream: ext://sys.stdout
    log_filename: ./logs/.log

rabbitmq:
    amqp_url: amqp://localhost:5672

serverless:
    backend: code_engine

ibm:
    iam_api_key: <key>

code_engine:
    namespace: <ns>
    runtime: ibmfunctions/lithops-ce-v385:234
    region: eu-de
    docker_server: de.icr.io
    docker_user: iamapikey
    docker_password: <key>

ibm_cos:
    ...
```

After a few seconds, my python script fails with the following error:
```sh
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/lithops/monitor.py", line 208, in run
    channel.basic_consume(self.queue, callback, auto_ack=True)
TypeError: basic_consume() got an unexpected keyword argument 'auto_ack'
```

Am I doing something wrong?

**Comment by JosepSampe** [comment]
Hi @REIGNjs, I think this might due to you have an old pika lib version on your machine, can you update your local pika installation? (pip3 install -U pika)

**Comment by REIGNjs** [comment]
Thanks, that fixed the issue even though there is a warning that lithops requires Pika 0.13.1: `lithops 2.3.4 requires pika==0.13.1, but you have pika 1.2.0 which is incompatible.`

The Code Engine Job does run now, but the console doesn't show any progress and the Job isn't automatically removed from the cloud engine project.
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/64702286/123093038-6f3ec900-d42b-11eb-81f1-c08b15ca7d4c.png">

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/64702286/123093100-87aee380-d42b-11eb-875e-e38d66f04b1e.png">

**Comment by JosepSampe** [comment]
Where do you have the rabbitmq service  installation? According to your config posted above, do you have it in localhost? Note that your rabbitmq service must be publicly accessible (with a public IP and open port)

**Comment by REIGNjs** [comment]
I tried moving the rabbitmq installation to an ubuntu 20.4 server, but the installation on ubuntu fails. Has probably something to do with the Erlang version. I am looking for a good way to measure the compute time of the cloud engine job. I want to compare the compute time of a VM that runs the image processing (Thumbnail generation with python Pillow) with traditional multiprocessing to lithops multiprocessing on cloud code engine.
The compute time of the VM can easily be measured with python, but lithops takes way longer, as it has to create and clean up the cloud engine job. I am looking for a way to only measure the compute time. Would appreciate your help

**Comment by JosepSampe** [comment]
You can see the function execution stats and 2 [execution plots](https://github.com/lithops-cloud/lithops/blob/master/docs/api_futures.md#executorplot) by accessing the low level Lithops executor, for example:

```python
import lithops.multiprocessing as mp


def my_map_function(x):
    time.sleep(5)
    return x + 7


if __name__ == '__main__':
    with mp.Pool() as pool:
        res = pool.map(my_map_function, [1, 2, 3])
        for fut in pool._executor.futures:
            print(fut.stats)
        pool._executor.plot(dst='~/lithops_test')
```

**Comment by REIGNjs** [comment]
Thanks, that works really well. I am writing a thesis for my university on Image Processing (Thumbnail generation) on Cloud Code Engine with Lithops Multiprocessing vs Image Processing on a Virtual Server. I am working for IBM and am doing an internship at Cloude Code Engine. Do you think the use case is valid? This is one of my first papers and i would appreciate any tips.
