### ISSUE TITLE
Deleted VM in IBM cloud when updating lithops

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#714]
During the transition from version 2.2.14 to 2.3.5, we are seeing the removal of the existing VM in IBM cloud. At the same time, we did not change the `exec_mode` key, by default it is `consume`. As far as I can see, changes have taken place in [this commit](https://github.com/lithops-cloud/lithops/commit/19372ca002ca1c8d8b93b6bac26142c2a576cb79). Is this a bug or should we change something in our code?

**Comment by JosepSampe** [comment]
@sergii-mamedov I think it was due a change that made old consume VMs incompatible with current consume VMs. I think If you create the consume VM again with Lithops 2.3.5 it won't be deleted anymore.

**Comment by sergii-mamedov** [comment]
@JosepSampe thank
