### ISSUE TITLE
Question about Code Engine

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#734]
What is the minimum docker image I need to run your applications inside CE? Now I see that you are based on `python:3.8-slim-buster` and then put a couple of [system dependencies](https://github.com/lithops-cloud/lithops/blob/master/runtime/code_engine/Dockerfile#L13-L25) and a rather large list of python [dependency](https://github.com/lithops-cloud/lithops/blob/master/runtime/code_engine/requirements.txt)? Are they all really needed? I am interested about `packages for numeric` and `Compose Libs` and also `kafka`, `redis`, `twisted` ...

Could you publish new image for `ibmfunctions/lithops-ce-v385` with support for version 2.4.0 on Docker Hub?

**Comment by JosepSampe** [comment]
@sergii-mamedov You can take this Dockerfile and add the python packages you need in the `pip install` (this dockerfile contains the minimum list of python libs required by lithops):

```dockerfile
# Python 3.6
#FROM python:3.6-slim-buster

# Python 3.7
#FROM python:3.7-slim-buster

# Python 3.8
FROM python:3.8-slim-buster

# Python 3.9
#FROM python:3.9-slim-buster

RUN apt-get update \
    # add some packages required for the pip install
    && apt-get install -y \
        gcc \
        zlib1g-dev \
        libxslt-dev \
        libxml2-dev \
        zip \
        unzip \
        make \
    # cleanup package lists, they are not used anymore in this image
    && rm -rf /var/lib/apt/lists/* \
    && apt-cache search linux-headers-generic

RUN pip install --upgrade pip setuptools six gevent \
    && pip install --no-cache-dir \
        simplejson \
        httplib2 \
        kafka_python \
        lxml \
        python-dateutil \
        pika \
        flask \
        gevent \
        ibm-cos-sdk \
        redis \
        requests \
        pandas \
        numpy \
        cloudpickle \
        ps-mem \
        tblib

ENV PORT 8080
ENV CONCURRENCY 4
ENV TIMEOUT 600
ENV PYTHONUNBUFFERED TRUE

# Copy Lithops proxy and lib to the container image.
ENV APP_HOME /lithops
WORKDIR $APP_HOME

COPY lithops_codeengine.zip .
RUN unzip lithops_codeengine.zip && rm lithops_codeengine.zip

CMD exec gunicorn --bind :$PORT --workers $CONCURRENCY --timeout $TIMEOUT lithopsentry:proxy
```


@gilv Could you create the `ibmfunctions/lithops-ce-v385:240` runtime?

**Comment by gilv** [comment]
@JosepSampe yeap

**Comment by gilv** [comment]
@sergii-mamedov @JosepSampe I released new Lithops version

**Comment by sergii-mamedov** [comment]
@gilv 
I do not see new release [here](https://hub.docker.com/r/ibmfunctions/lithops-ce-v385/tags?page=1&ordering=last_updated)

**Comment by sergii-mamedov** [comment]
@JosepSampe 
I have seen the given code. My question was more about whether this minimal image really needs `numpy`,` pandas` ...?
