### ISSUE TITLE
Dockerfile for Code Engine

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#738]
As part of the Cloud Function (CF) migration to the Code Engine (CE), I did a dependency analysis that is used for both options. It turned out that the proposed [Dockerfiles](https://github.com/lithops-cloud/lithops/blob/master/runtime/code_engine/Dockerfile) contained an excessive number of dependencies. For example CE Dockerfile:

1. In the `apt-get` section, only` unzip` is required.
2. In the `pip` section (dependencies sorted alphabetically). I think removing unused dependencies would reduce the size of the Docker image and speed up the start of CF and CE.
```
                | necessary |    comments 
----------------------------------------------
cloudpickle     |    yes    |
flask           |    yes    |
gevent          |  may be   | only for lithops/standalone/master.py
gunicorn        |    yes    |
httplib2        |     no    | only for GCP
ibm-cos-sdk     |    yes    |
kafka           |     no    |
lxml            |     no    |
numpy           |    yes    |
pandas          |    yes    |
pika            |    yes    |
ps-men          |    yes    |
python-dateutil |     no    |
redis           |    yes    |
requests        |    yes    |
simple-json     |     no    |
tblib           |    yes    |
```

3. There is no information about the file [lithops_codeengine.zip](https://github.com/lithops-cloud/lithops/blob/master/runtime/code_engine/Dockerfile#L39-L40). I figured it out, but I think it would be good to describe this point in the documentation.

**Comment by gilv** [comment]
@sergii-mamedov this zip file is not something users need to touch. What kind of information you feel is missing? The dependencies perhaps not optimized or contain broad scope of packages...you  can remove some of them based on your needs

**Comment by sergii-mamedov** [comment]
@gilv The problem is that if I want to build my image, I need the `lithops_codeengine.zip` file. Or if I want to build it for a fresh version for which you don't have a docker image yet.
Unfortunately, in the repository you do not provide either the file itself or instructions on how to create it.
P.S. I figured out how to do it.

**Comment by gilv** [comment]
@sergii-mamedov you must use Lithops to build images, not you to build it somehow. Lithops create runtme is what exactly suppose to do

**Comment by gilv** [comment]
@sergii-mamedov file is created automatically by lithops create runtime. Nobody suppose to create it manually

**Comment by gilv** [comment]
@sergii-mamedov https://github.com/lithops-cloud/lithops/tree/master/runtime/code_engine

**Comment by gilv** [comment]
@LachlanStuart can you show @sergii-mamedov how you created runtimes?

**Comment by sergii-mamedov** [comment]
He looked at it. My PR [here](https://github.com/metaspace2020/metaspace/pull/916).

**Comment by sergii-mamedov** [comment]
@gilv 
Also a very strange limitation on the presence of dots in the docker image tag name. 
```
Exception: Invalid docker image name: All letters must be lowercase and '.' or '_' characters are not allowed
```
Docker documentation allows any [ASCII characters](https://docs.docker.com/engine/reference/commandline/tag/).

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.
