### ISSUE TITLE
lithops[aws] package not existent

### ISSUE THREAD

**Issue by h4gen** [lithops-cloud/lithops#749]
When I want to prepare Lithops by installing lithops[aws] as described [here](https://github.com/lithops-cloud/lithops/blob/master/config/compute/aws_lambda.md) with
`$ python3 -m pip install lithops[aws]`

I get the following error:
`no matches found: lithops[aws]`

Also pypi knows no such package :(

**Comment by JosepSampe** [comment]
@h4gen just ran the command and it seems to work ok. I'm not sure what might be the cause that makes it fail in your case. In any case, lithops in AWS only needs the boto3 lib, so you can run the next command with the same effect:  `$ python3 -m pip install lithops boto3`

**Comment by h4gen** [comment]
Hi @JosepSampe thanks for getting back. I also ran the command on another PC and it did not work either. In both cases both are conda base environments with python3 (Standard conda installation). Will try your workaround.

**Comment by JosepSampe** [comment]
@h4gen Thanks for the context information. Its weird because the lib is in the pypi repo https://pypi.org/project/lithops and this command always worked ok in standard python installations. Could it be that this conda env is using some cache where Lithops is not present?

**Comment by h4gen** [comment]
So just to clarify this. The installation of lithops itself via `pip install lithops` works flawlessly, only `python3 -m pip install lithops[aws]` makes problems.

**Comment by JosepSampe** [comment]
I tried to run it in a conda environemnt using a conda docker image, and it worked ok:
```
josep@cloudlab04:~$ docker run -it continuumio/miniconda3 /bin/bash
(base) root@5648a176e893:/# pip install -U lithops[aws]
Collecting lithops[aws]
  Downloading lithops-2.4.1-py3-none-any.whl (277 kB)
     |████████████████████████████████| 277 kB 1.6 MB/s 
```
I also installed conda on my machine and ran the command successfully:
```
(base) josep@cloudlab04:~$ pip install -U lithops[aws]
Collecting lithops[aws]
  Downloading lithops-2.4.1-py3-none-any.whl (277 kB)
     |████████████████████████████████| 277 kB 1.6 MB/s 
```



So i wonder if it is something wrong in your local installation. It is weird because we never had problems with this.
