### ISSUE TITLE
pickle future objects

### ISSUE THREAD

**Issue by DhavalRepo18** [lithops-cloud/lithops#752]
Is there any way we can pickle future object? 

import dill
submited = lithops.FunctionExecutor(...)
dill.dump(submited, open('test_w.pkl','w'))

?? Any suggestion... submission via one node, result tracking via another node? 
Spceially code engine which can run a longer job we shd be able to do 
- load()
- dump() on future object.

**Comment by gilv** [comment]
@JosepSampe any thoughts?

**Comment by JosepSampe** [comment]
@DhavalRepo18 In the example above you are trying to pickle the whole function executor (not the futures), and it is not possible to pickle the function executor. 

Futures are generated when you call a map(), so in this case you can pickle futures doing something like:

```python
import dill
executor= lithops.FunctionExecutor(...)
futures = executor.map(.....)
dill.dump(futures, open('test_w.pkl','w'))
```
