### ISSUE TITLE
No lambda concurrency with map()

### ISSUE THREAD

**Issue by FTWH** [lithops-cloud/lithops#762]
I use lithops with lambda backend to test a map() computation stage. All the jobs are handled by the same lambda function in multi-process. How to configure it to enable actual concurrency in lambda workers?

**Comment by JosepSampe** [comment]
Function concurrency is enabled by default in all backends  (up to 1000 functions)

For example:
![test_us_east_histogram](https://user-images.githubusercontent.com/10448186/132941037-7d4f30a6-b1b0-42bc-a8c4-e07721133884.png)

In principle, the only way to limit concurrency is by manually setting ithops workers to a lower value.

Can you provide more information about your experiment? Which lithops api are you using? can you post here your config file (hiding your keys)? can you post the code to replicate the issue? can you post the same plot I posted above?

**Comment by FTWH** [comment]
Thanks a lot for your help. There is no problem at all.
