### ISSUE TITLE
podman support?

### ISSUE THREAD

**Issue by rmey** [lithops-cloud/lithops#774]
Would it be possible to add podman support for lithops instead of docker only?
Some Mac OSX users switching to podman.

**Comment by JosepSampe** [comment]
@rmey As far as I know, `podaman` and `docker` has similar (or the same) set of parameters. Is that right? If you set `alias docker=podman` then all the commands in lithops would be executed in podman, right?

Is it is the case we can create a new lithops config key for defining which container tool to use, for example:

```yaml
lithops:
   ...
   container_orchetrator: podman
```

**Comment by rmey** [comment]
Thank you will try this on my mac with brew based install of podman.

**Comment by rmey** [comment]
It works with brew based podman install. I was also able to build a custom runtime matching my local python versions in a pyenv.
I created a logic link /usr/local/bin/podman pointing to /usr/local/bin/docker
