### ISSUE TITLE
Push new CE runtime alongside each release

### ISSUE THREAD

**Issue by Cohen-J-Omer** [lithops-cloud/lithops#784]
Hello @JosepSampe and @gilv,
I believe that with each new release, we need to push the CE runtime of said release (lithops) to the official docker repository. 
I assume the following is lithops' docker repository: https://hub.docker.com/r/ibmfunctions/lithops-ce-v385/tags. 

What do you guys think?

**Comment by JosepSampe** [comment]
In my case I don't have write access to this repo. @gilv ^^
