### ISSUE TITLE
Removing temporary files

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#822]
When upgrading from version 2.5.0, some of our tests was failed. The reason for this was the handling of [this error](https://github.com/lithops-cloud/lithops/commit/bd59d261204fcb0e58ad0376bb3dcd6a72f223bf#diff-7caf33b04d29735b179f5cde1a693da8523d62b84cb8bbaa43e2f6cb25477a73R165)(?). However, at the moment I am somewhat confused by the logic of the ёdelete_objectsё function. The function description and common sense suggest that only files transferred in the `key_list` variable should be deleted. The last lines of this function delete the entire directory with all temporary files.
In our tests, we give verification of each launch of the lithops executor, so we need temporary files from the previous step.
Is it possible to remove this [if statement](https://github.com/lithops-cloud/lithops/blob/master/lithops/storage/backends/localhost/localhost.py#L164-L165), or at least make it optional?

**Comment by sergii-mamedov** [comment]
@giarve could you create a new release?

**Comment by JosepSampe** [comment]
@gilv ^^
