### ISSUE TITLE
ARM64 / AMD64

### ISSUE THREAD

**Issue by vysecurity** [lithops-cloud/lithops#879]
1) Appears to be no way to force AMD64 in the Dockerfile for the `lithops runtime build` command. The image pulled doesn't appear to support x86-64 architecture?

2) Is there any way to specify the use of ARM64 Lambda instances?

Tried:

`FROM --platform=linux/amd64 python:buster as build-image`

**Comment by vysecurity** [comment]
Fixed, I missed a reference in my DockerFile.

**Comment by vysecurity** [comment]
Actually, question 2 still stands. Any way to specify ARM64 lambda instances?

**Comment by JosepSampe** [comment]
@vysecurity With #880  You can now set the architecture type in your config file, for example:
```yaml
aws_lambda:
    architecture: arm64
```

You might consider using an AMR64 python base image for your dockerfile from: https://gallery.ecr.aws/lambda/python, _IMAGE TAGS_ tab

**Comment by vysecurity** [comment]
Thanks! Let me give that a shot and feedback here.

**Comment by vysecurity** [comment]
I built a Docker based on ARM64, then tried to add that flag into config file and it ended up getting Python exec error on runtime which indicates an architecture issue.

**Comment by JosepSampe** [comment]
@vysecurity Both the client and the runtime must run the same python version due a [cloupickle ](https://github.com/cloudpipe/cloudpickle) restriction. 

According to the error message, your docker runtime has python3.8 and not python3.9. Try using python3.8 in your local machine, or review your dockerfile and ensure that python3.9 is included there.

**Comment by vysecurity** [comment]
Got it in the end thanks

**Comment by JosepSampe** [comment]
@vysecurity So, is this solved? Have you been able to run lithops functions with an arm runtime at the end?

**Comment by vysecurity** [comment]
Solved! Sorry for late response :-)

**Comment by JosepSampe** [comment]
Cool! thank you
