### ISSUE TITLE
bucket used by PyWren and bucket used as input data

### ISSUE THREAD

**Issue by gilv** [lithops-cloud/lithops#90]
Currently we extract bucket_name from provided path.
For example 

     pw.map(my_func, 'data/input/d.txt')

PyWren will use 'data' as a bucket name and 'input/d.txt' as a key.
However the endpoint and credentials are used defined in the config, cos section. This section defines credentials for the bucket used by PyWren, defined in 'storage_bucket'

Thus if "data" bucket doesn't exists in the same region or has different access key, exception will happen that no bucket exists.

As a temporary work around, we need to make sure that bucket used by PyWren has the same edpoint and same credentials as bucket used for the input data in map().

**Comment by JosepSampe** [comment]
@gilv I was thinking how to face this, and I saw that IBM COS buckets and objects already contain an "SQL URL" in the COS dashboard. To get this url, you have to go to the last "tree points"(Bucket Actions) of the bucket row (as shown in the image):
![ibm_cos](https://user-images.githubusercontent.com/10448186/54839792-ea085f00-4ccb-11e9-9d32-b5e94567c0bd.png)

And the select and select "**SQL URL**":
![sql_url](https://user-images.githubusercontent.com/10448186/54839941-2b990a00-4ccc-11e9-8593-cc2a4b6adbbf.png)

As you can see, the **url** contains the region. 
Now, we only write the bucket name in a string when we want to process the objects of a bucket, but I think this **url** is the correct format to do it. 
Then, the connexion to COS can be managed internally, and transparently, by PyWren, even for multiple regions.

**Comment by gilv** [comment]
@JosepSampe this is not only about endpoint URL. Bucket used to read and bucket used by PyWren internaly may have different access credentials.

**Comment by omerb01** [comment]
@gilv why is that a problem? does work with different regions really matters? I think the correct thing is to assume that every pywren's execution happens in a specific region provided in config file.

**Comment by gilv** [comment]
@omerb01 we want option to read from one bucket where the data is and PyWren will use another bucket for it's pickle, etc.

**Comment by omerb01** [comment]
@gilv also issue #81 can be solved by this way - a dedicated bucket for pywren's inner data that created automatically in init, and then we can make sure that this bucket is entirely empty by delete everything inside.

**Comment by gilv** [comment]
@omerb01 we can auto-create as an option, but default should be provided by the user

**Comment by omerb01** [comment]
@gilv I will explain what I mean in details:
we want to separate inner data storage and user data input - so I think that should be a different bucket for pywren's inner data which created automatically by pywren and the user won't even know that it exists - only pywren will work with this bucket for its needs cause the user shouldn't expose to this data and shouldn't use it.
If the user will use storage for his data, he can provide a bucket that created manually by him, in the same region that in config file.
so in terms of configurations - in this way we only need credentials in a specific region without providing a bucket.

what do you think?

**Comment by JosepSampe** [comment]
@omerb01 @gilv Correct me if I'm wrong, but as far as I know, with "COS Service credentials" you can access to any bucket located in any region. I mean, you don't need different credentials to access each region, so by using that URL, a user can use any bucket located anywhere with same credentials.

**Comment by gilv** [comment]
@JosepSampe nope...it API key per bucket. For example i can create one API key with read only access and provide it to you...you will use PyWren to read data and process it, while you will use your own bucket for PyWren internal stuff

**Comment by gilv** [comment]
@JosepSampe does ^^^  makes more clear now the need for this change?

**Comment by torsstei** [comment]
In really like the suggestion of @JosepSampe to leverage the "SQL URL" in COS UI also as input format for pywren data stream. We can easily generalize the name in COS UI to be something like "Query URL" or so.

@gilv I think it is OK to assume by default the same IAM API key  to use for pywren internal status bucket as well as for the data stream bucket. You may consider an optional config property for pywren internal cos in case it should be different. 

Along with the need to also support IAM API key for cloud functions I suggest to start supporting a new top level pywren config property called ibm_iam with a sub property ibm_iam.api_key. When this is provided and you don't find (the then optional) ibm_cos.api_key and also not (the then optional) ibm_cf.api_key then you use the same IAM key for all three: 1. cloud functions, 2. COS input data bucket, 3. internal COS status bucket. That allows a convenient default SSO behavior. By still allowing special keys for internal COS and for cloud functions you have an option for users who may need to opt out of this SSO.

**Comment by JosepSampe** [comment]
Closing this for now as it never became relevant, since it is always better to move the data to a personal bucket.
