### ISSUE TITLE
What if the concurrency processes for a AWS Lambda function exceed its memory?

### ISSUE THREAD

**Issue by FTWH** [lithops-cloud/lithops#917]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/71968506/169438902-3a64d37b-0329-4b31-8d1a-5eeb0c4b1936.png">
As above, we can configure the worker_process in each lambda instance. But what if the resource consumption exceeds the limitation of function instances? Will lithops handle this situation? Thanks a lot!

**Comment by JosepSampe** [comment]
@FTWH At this moment Lithops is not habdling this situation and you will receive a `MemoryError` Exception
