### ISSUE TITLE
Inconsistent chunk size for map and obj_chunk_size

### ISSUE THREAD

**Issue by locotron** [lithops-cloud/lithops#930]
I'm trying to read a file in parallel using multiple workers, with a lithops map. I have encountered a strange issue that i cannot explain.

What im trying is to generate metadata chunks from a bigger file.
The code for the worker function is as follows:
```
 #Generate metadata from fasta file
    def generate_metadata(self,obj):
        data = obj.data_stream.read()
        print('len_data:'+str(len(data)))
        print('chunk_size:'+str(obj.chunk_size))
        print('byte_range:' + str(obj.data_byte_range[1]-obj.data_byte_range[0]))
```

The main:

```
if __name__ == "__main__":
    fexec = lithops.FunctionExecutor(
        log_level='DEBUG',runtime='testcontainer',storage='localhost',backend='localhost')
    
    args = {'obj':'/mnt/c/Users/ayman/Desktop/fasta.fasta', 'bucket_name':'data'}
    
    
    fexec.map(run_worker_metadata, args,
              obj_chunk_size=2000000)
    fexec.wait())


    res = fexec.get_result()
 
    fexec.clean()
```

The issue is that the three variables have different sizes, and the size of the data variable keeps changing deppending on which worker it is.

The log file is attached, so it can be reviewed carefully:

[728009-0-M000.log](https://github.com/lithops-cloud/lithops/files/8777775/728009-0-M000.log)

Thanks!

**Comment by JosepSampe** [comment]
@locotron do you refer to the `len_data` value in the logs?

**Comment by locotron** [comment]
Yes, but also bj.data_byte_range[1]-obj.data_byte_range[0] shouldn't be the same as obj.chunk_size?

**Comment by JosepSampe** [comment]
I don't see the data, but I think this is not an issue. 

When Lithops splits a file in multiple parts for processing, it makes sure that no worker receives a partial line due a fixed chunk_size. In this sense, the internal Lithops mechanism always sends some extra data to each worker to ensure that all the workers will receive entire lines. This is why you see obj.data_byte_range[1]-obj.data_byte_range[0] = 2131072, which is 2000000 (that you set) + 131072 of extra data for keeping line integrity. Then Lithops discards most of this extra data, because the system only wants some extra bytes to make sure that the last line of the chunk is not partial, this is why you then see that the chunk is sometimes  2000010, or 2000004 or whatever else.

Check this https://github.com/lithops-cloud/lithops/blob/master/docs/source/data_partitioning.rst#keeping-line-integrity-in-mind

**Comment by locotron** [comment]
Okay, i see. That was what @giarve explained to me, also credits for helping me find a solution. 

Since i need consistent chunks between workers, so that i know what the previous worker has read i ended up using the WrappedStreamingBody read method, that doesn't care about consistency and always reads the same number of bytes.

Thank you very much @JosepSampe.

**Comment by aitorarjona** [comment]
@JosepSampe Just to clarify, this procedure is executed always when `obj_chunk_size` or `obj_chunk_number` is specified right? Then, for text based files like CSV is ok, but muy concern is if this is used in other arbitrary binary formats where `\n` is not present. Would this be then an overhead, or produce unaccurate chunks? Maybe this feature can be executed for `text/*` MIME type objects, but ignored for other formats. Or the user could specify with a parameter a delimiter, by default could be `\n` (text-based partitioner enabled) and `None` to bypass the partitioner

**Comment by JosepSampe** [comment]
The main problem I see using `obj.data_stream.read()` is that each worker will receive the extra data anyway, so at the end there will be duplicate data. So I think the best option, if we want to handle this , is to create an additional parameter in the map/map_reduce functions to activate or bypass the partitioner

**Comment by JosepSampe** [comment]
I've been thinking on this, and found that the built-in python [`open()`](https://docs.python.org/3/library/functions.html#open) method use he parameter `newline` to specify the character that split lines. Currently Lithops has `obj_chunk_size` and `obj_chunk_number`, so we could add `obj_newline`, this way a user could set it to `None` to disable all the internal "line-integrity" logic and get chunks of the exact same size in the functions
