### ISSUE TITLE
Allow progress bar to be turned off

### ISSUE THREAD

**Issue by tomwhite** [lithops-cloud/lithops#971]
The only way I have found to disable the progress bar is by changing the log level:

```python
import logging
logging.getLogger("lithops.wait").setLevel(logging.WARNING)
```

It would be nice to be able to do this via a parameter in [wait](https://lithops-cloud.github.io/docs/source/api_futures.html#lithops.executors.FunctionExecutor.wait).

I want to do this so I can manage my own progress bars that aggregate a number of lithops operations in one.

**Comment by JosepSampe** [comment]
@tomwhite Added in master branch. It can now be disabled by setting `fexec.wait(show_progressbar=False)`

**Comment by gilv** [comment]
@tomwhite can we close this issue? I will draft new release of Lithops today

**Comment by tomwhite** [comment]
I just tested this (back from vacation today) and it worked fine. Thanks @JosepSampe and @gilv!
