### ISSUE TITLE
Wish: build images in the cloud

### ISSUE THREAD

**Issue by tomwhite** [lithops-cloud/lithops#972]
This would help reduce friction when getting started since there would be no need to install docker, and it would avoid a large upload (multi-GB potentially).

Is this something that has been considered before?

**Comment by gilv** [comment]
@tomwhite can you be more specific on the way you thought this will work? otherwise there might be various ways to make this

**Comment by tomwhite** [comment]
I thought that for AWS Lambda it might be possible to use [AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html) to produce a docker image and publish it to a repository. I haven't tried this though.

**Comment by gilv** [comment]
@tomwhite I wonder what would be more complicated for a novice user ;) : install Docker client locally and wait a bit for uploading images or learn how to use AWS CodeBuild, read documentation there, experiment with it, debug it when something not working, etc... :)

**Comment by tomwhite** [comment]
I was imagining that Lithops would hide the CodeBuild part, in the same way that it hides the runtime build and deploy steps already. In other words, `lithops runtime build --remote` (or similar) would just do the build in the cloud instead of locally.

**Comment by gilv** [comment]
@JosepSampe what do you think?

**Comment by JosepSampe** [comment]
In the past we have been using Tekton for the Knative backend.
We can explore AWS CodeBuild for AWS backends.

**Comment by JosepSampe** [comment]
Closing due inactivity
