### ISSUE TITLE
Can't set ModuleDependencyAnalyzer log level

### ISSUE THREAD

**Issue by tomwhite** [lithops-cloud/lithops#986]
When trying to debug which modules are being transmitted, setting

```
lithops:
  log_level: DEBUG
```

doesn't show any messages from `ModuleDependencyAnalyzer`.

This doesn't seem to work either (in an example script):

```
logging.getLogger("multyvac.dependency-analyzer").setLevel(logging.DEBUG)
```

Should the logger in `ModuleDependencyAnalyzer` be changed to be like the other ones in Lithops?

**Comment by gilv** [comment]
@JosepSampe any thoughts?

**Comment by JosepSampe** [comment]
Checking it

**Comment by JosepSampe** [comment]
#994 Should be enough to show the logs from the module_dependency.py at the same level set in Lithops
