### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by ShuxinLin** [lithops-cloud/lithops#993]
Hi, I am checking how lithops can do with k8s. I read through the docs https://github.com/lithops-cloud/lithops/tree/master/runtime/kubernetes. I found no words on setting the k8s context etc. I am wondering if lithops supports it? Say I have a cloud k8s cluster. Does lithops help deploying pods on the cluster?

**Comment by JosepSampe** [comment]
Yes, you can run Lithops in any k8s cluster. You only need the kube config file in the correct place. If you have the kube config file, and you can use the `kubectl` command to operate your cluster, then Lithops will be able to automatically deploy all the necessary stuff needed to run the functions.

**Comment by ShuxinLin** [comment]
@JosepSampe thank you. What if I want to deploy dockers from private registry. If it is code engine, I follow this config https://github.com/lithops-cloud/lithops/blob/c6a028f540ca6101382bd38403dfd6036c256394/config/config_template.yaml#L44. I found no k8s section in config template, is that similar to code engine?

**Comment by JosepSampe** [comment]
Yes, it's the same. Check this https://github.com/lithops-cloud/lithops/blob/master/docs/source/compute_config/k8s_job.md#configure-a-private-container-registry-for-your-runtime

**Comment by ShuxinLin** [comment]
Thank you. I will take a look at this page.
